// Declaração dos plugins
// plugins {}
Provider<Map<String, String>> propsProv = providers.of(LeitorProps) { 
    parameters.propertiesFile = rootProject.layout.projectDirectory.file(
        providers.gradleProperty('localPropertiesNome')
    )
}
// Configuração das ferramentas de compilação. Garante o uso do compilador correto
toolChains {
    // Diz para o Gradle procurar especificamente pelo Gcc
    if (System.getProperty('os.name').toLowerCase().contains('windows')) {
        String msysDir = "${propsProv.get().getOrDefault('unidade.win', 'C')}:/msys64"

        visualCpp(VisualCpp)

        mingwX86(Gcc) { path "${msysDir}/mingw32/bin" }

        ucrtX64(Gcc) { path "${msysDir}/ucrt64/bin" }
    }

    gcc(Gcc) // generalizado, funciona para windows e linux, 64 e 32
}
// Biblioteras para serem usadas no código
// dependencies {}