// Declaração de plugins
// plugins {}
// Atalhos para facilitar a leitura
Object propsLocal = gradle.ext.propsLocal
// Provedores para acesso lazy às variáveis
Provider<Boolean> eWindowsProv = providers.systemProperty('os.name').map {
    it.toLowerCase().contains('windows')
}
Provider<Directory> buildDirProv = project.layout.buildDirectory
Provider<Directory> deployDirProv = buildDirProv.dir('distributions')
Provider<String> nomeAppProv = providers.gradleProperty('projNome')
Provider<String> espNomeProv = providers.gradleProperty('espolioDir').orElse('espolio')
Provider<String> verNumProv = providers.gradleProperty('appVerNum')
Provider<Boolean> jarMagroProv = project.providers.gradleProperty('buildMagroWeb').map { 
    it.toBoolean() }.orElse( project.providers.provider { 
        gradle.startParameter.taskNames.contains('submitWeb') //verifica qual tarefa chamou o build
    })
// Tarefas personalizadas
tasks.named('jar') { enabled = false } // destivado para não gerar jar parciais
// Configurado para alterar o nome do jar gerado e otimizar o tamanho do arquivo
tasks.named('bootJar') { // Compilador padrão
    onlyIf{ !jarMagroProv.get() }

    mustRunAfter tasks.named('minWebJar')
    inputs.files(tasks.named('minWebJar'))

    archiveBaseName.set(nomeAppProv)
    archiveVersion.set(verNumProv)
    archiveClassifier.set('')
    destinationDirectory.set(deployDirProv)
    // Injeta as classes otimizadas pelo ProGuard
    from({ zipTree(buildDirProv.file('intermediates/minified-project.jar' )) }) {
        into 'BOOT-INF/classes'
    }
    // Filtra o classpath, mantem todas os .jar, remove pastas locais que o ProGuard processou
    classpath = classpath.filter { File arq ->
        arq.isFile() && 
        arq.name.endsWith('.jar') &&
        !arq.name.contains('spring-boot-jarmode-tools') &&
        !arq.name.contains('bib-lista') // remove o JAR duplicado
    }
    
    exclude 'main/**', '**/classpath.idx', '**/layers.idx', '**/spring-boot-jarmode-tools-*.jar'
    exclude 'BOOT-INF/classpath.idx', 'BOOT-INF/layers.idx'
    entryCompression = ZipEntryCompression.DEFLATED
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
// Configurado para alterar o nome do jar gerado e otimizar o tamanho dos arquivos
tasks.register('orderJar', Jar) { // Compilador secundário -Pthin=true
    group = 'WebActions'
    description = 'Gera o JAR magro e copia as dependências para a pasta lib/'
    onlyIf{ jarMagroProv.get() }

    mustRunAfter tasks.named('minWebJar')
    inputs.files(tasks.named('minWebJar'))
    finalizedBy tasks.named('orderLibs')
    
    archiveBaseName.set(nomeAppProv)
    archiveVersion.set(verNumProv)
    archiveClassifier.set('')
    destinationDirectory.set(deployDirProv)
    // Puxa apenas o zip do ProGuard
    from({ zipTree(buildDirProv.file('intermediates/minified-project.jar')) })
    
    manifest {
        attributes(
            'Main-Class': 'com.oboco.web.LoggerApplication',
            'Class-Path': project.providers.provider {
                configurations.runtimeClasspath.files
                    .findAll { !it.name.startsWith('bib-lista') }
                    .collect { "lib/${it.name}" }.join(' ')
            }
        )
    }
}
// Cria cópia das Libs separadamente
tasks.register('orderLibs', Copy) {
    group = 'WebActions'
    description = 'Copia as dependências para a pasta lib/'
    onlyIf{ jarMagroProv.get() }

    mustRunAfter tasks.named('orderJar') // obriga o JAR ser gerado primeiro
    
    into deployDirProv.map { it.dir('lib') }
    from configurations.runtimeClasspath
    exclude 'spring-boot-jarmode-tools-*.jar'
}
// Apaga a pasta do inteira de build
tasks.register('cleanWeb') {
    group = 'WebActions'
    description = 'Limpa o ambiente java web, para testes completos'
    outputs.upToDateWhen { false }
    finalizedBy tasks.named('clean')
}
// Minifica os jar gerados
tasks.register('minWebJar', proguard.gradle.ProGuardTask) {
    mustRunAfter tasks.named('classes')
    inputs.files(tasks.named('classes'))
    injars sourceSets.main.output, filter: '!main/' // pega as saídas compiladas
    // .jar temporário apenas com classes magras
    Provider<RegularFile> miniJarProv = buildDirProv.file('intermediates/minified-project.jar')
    outjars miniJarProv
    libraryjars "${System.getProperty('java.home')}/jmods"
    // Referencia as libs externas mas não inclui no processo de encolhimento
    libraryjars configurations.runtimeClasspath
    configuration file('proguard-web.pro')

    doFirst {
        File miniJar = miniJarProv.get().asFile
        if (miniJar.exists()) miniJar.delete()
        miniJar.parentFile.mkdirs()
    }
}
// Compilação do aplicativo
tasks.register('buildWeb') {
    group = 'WebActions'
    mustRunAfter(jarMagroProv.map { boolean eThin -> 
        eThin ? tasks.named('orderJar') : tasks.named('bootJar') 
    })
    inputs.files(jarMagroProv.map { boolean eThin -> 
        eThin ? tasks.named('orderJar') : tasks.named('bootJar') 
    })
    outputs.file(buildDirProv.file(nomeAppProv.flatMap 
        { String nome -> verNumProv.map { String ver -> "distributions/${nome}-${ver}.jar" } }
    ))
}
// Roda em terminal externo
tasks.register('runWeb') { // http://localhost:8080
    group = 'WebActions'
    description = 'Executa se o JAR já existente na pasta lib'
    mustRunAfter assemble // só tenta rodar se o arquivo realmente existir
    inputs.files(tasks.named('buildWeb'))
    outputs.upToDateWhen { false }

    doFirst {
        File deployDir = deployDirProv.get().asFile
        File jarArq = deployDir.listFiles()?.find { it.isFile() && it.name.endsWith('.jar') }
        
        if (jarArq == null || !jarArq.exists()) {
             throw new GradleException("JAR magro não encontrado em ${deployDir.absolutePath}")
        }

        ProcessBuilder pb
        if (System.getProperty('os.name').toLowerCase().contains('windows')) {
            pb = new ProcessBuilder('cmd', '/c', 'start', 'cmd', '/k', 'java', '-jar', jarArq.name)
        } else { pb = new ProcessBuilder('sh', '-c', 'java', '-jar', jarArq.name, '&') }

        pb.directory(deployDir)
        pb.start()
    }

    doLast {
        println ('>> INFO: Aplicação web disponível em http://localhost:8080')
    }
}
// Realiza todos os testes
tasks.register('testWeb') {
    group = 'WebActions'
    description = 'Realiza os testes para o aplicativo web'
    finalizedBy tasks.named('check')
    finalizedBy tasks.named('test')
}
// Garante a saída dos resultados dos testes
tasks.withType(Test).configureEach {
    outputs.upToDateWhen { false }

    useJUnitPlatform() // liga o motor de testes do JUnit Platform

    jvmArgs('-Xshare:off') // desliga o Class Data Sharing para evitar o warning da JVM 
    jvmArgs('-XX:+EnableDynamicAgentLoading') // permite o Mockito a injetar o agente de testes

    systemProperty 'spring.main.banner-mode', 'off' // desliga o Logo ASCII gigante do Spring
    systemProperty 'logging.level.root', 'WARN' // esconde os INFOs de inicio

    testLogging {
        events 'passed', 'skipped', 'failed' // mostra no terminal os testes
        showStandardStreams = false // saída padrão do console
        // Se der erro, mostra a origem do problema
        exceptionFormat = 'full'
        showCauses = true
        showStackTraces = true
    }

    addTestListener(new org.gradle.api.tasks.testing.TestListener() {
        void beforeSuite(org.gradle.api.tasks.testing.TestDescriptor suite) {}
        void beforeTest(org.gradle.api.tasks.testing.TestDescriptor test) {}
        void afterTest(
            org.gradle.api.tasks.testing.TestDescriptor test, 
            org.gradle.api.tasks.testing.TestResult result
        ) {}
        void afterSuite(
            org.gradle.api.tasks.testing.TestDescriptor desc, 
            org.gradle.api.tasks.testing.TestResult result) {
            // Garante que é a execução raiz de todos os testes
            if (!desc.parent) { 
                println '\n======================================================================='
                println "RESULTADO DOS TESTES: ${result.resultType}"
                println """\
                    || Total de testes: ${result.testCount} |
                    | sucessos: ${result.successfulTestCount} |
                    | falhas: ${result.failedTestCount} |
                    | pulados: ${result.skippedTestCount} ||""".stripIndent().replaceAll('\n', '')
                println '======================================================================='
            }
        }
    })
}
// Cria um ícone para a página web
tasks.register('webIco') {
    group = 'Web Actions'
    description = 'Gera o icone.png para a aplicação Web'

    Provider<RegularFile> fundoSvgProv = espNomeProv.map {
        project.rootProject.layout.projectDirectory.file("${it}/icones/appBackground.svg")
    }
    Provider<RegularFile> frenteSvgProv = espNomeProv.map {
        project.rootProject.layout.projectDirectory.file("${it}/icones/appForeground.svg")
    }
    Provider<RegularFile> pngArqProv = buildDirProv.file('generated/webIcoRes/static/favicon.png')
    
    inputs.files(fundoSvgProv, frenteSvgProv)
    outputs.file pngArqProv
    
    doLast {
        File fundoSVG = fundoSvgProv.get().asFile
        File frenteSVG = frenteSvgProv.get().asFile
        File pngArq = pngArqProv.get().asFile
        if (!fundoSVG.exists()) throw new GradleException('Faltou o SVG de Fundo!')
        if (!frenteSVG.exists()) throw new GradleException('Faltou o SVG de Frente!')
        
        File buildDir = pngArq.parentFile
        if (!buildDir.exists()) buildDir.mkdirs()
        
        Process processo = [
            eWindowsProv.get() 
            ? "${propsLocal.getProperty('unidade.win', 'C')}:/msys64/ucrt64/bin/magick.exe" 
            : 'magick',
            '-background', 'none',
            fundoSVG.absolutePath, 
            frenteSVG.absolutePath, 
            '-gravity', 'center', 
            '-composite', 
            '-resize', '2048x2048', 
            pngArq.absolutePath 
        ].execute()
        processo.waitForProcessOutput(System.out, System.err)
        if (processo.exitValue() != 0) {
            throw new GradleException('Falha ao gerar o ícone da Web')
        }
    }
}
// Evia a nova versão para o servidor
tasks.register('submitWeb') {
    group = 'deploy actions'
    description = 'Envia os arquivos para o servidor remoto'
    mustRunAfter(tasks.named('orderJar'))
    mustRunAfter(tasks.named('orderLibs'))
    inputs.files(tasks.named('orderJar')) // usa os jar magros para ser mais rápido
    inputs.files(tasks.named('orderLibs'))

    doLast {
        String dono = propsLocal.getProperty('srv.dono')
        String sede = propsLocal.getProperty('srv.sede')
        String dir = propsLocal.getProperty('srv.dir')
        String servico = propsLocal.getProperty('srv.servico')
        String appJar = "${nomeAppProv.get().toString().toLowerCase()}.jar"

        if (!dono || !sede || !dir) {
            throw new GradleException('Faltam variáveis do servidor no local.properties!')
        }

        File baseLocaldir = deployDirProv.get().asFile
        if (!baseLocaldir.exists()) {
            throw new GradleException("A pasta base de compilação (${baseLocaldir}) não existe!")
        }

        Map<String, String> hashesMap = [:]
        ByteArrayOutputStream saidaStd = new ByteArrayOutputStream()
        ByteArrayOutputStream erroStd = new ByteArrayOutputStream()
        
        Process processoHash = [
            'ssh', '-o', 'StrictHostKeyChecking=no', "${dono}@${sede}", 
            "cd ${dir} 2>/dev/null && find . -type f -exec md5sum {} + || true"
        ].execute()
        processoHash.waitForProcessOutput(saidaStd, erroStd)
        
        if (processoHash.exitValue() != 0) {
            throw new GradleException('' +
                'Falha de conexão com o servidor ao ler os Hashes! \n' +
                "Detalhes: ${erroStd.toString().trim()}"
            )
        }

        saidaStd.toString().eachLine { String linha ->
            linha = linha.trim()
            if (linha && linha.contains('  ')) {
                List<String> partes = linha.split('  ')
                if (partes.size() >= 2) {
                    // Remove o './' que o comando 'find' do Linux coloca no começo do caminho 
                    hashesMap[partes[1].trim().replaceFirst('^\\./', '')] = partes[0].trim()
                }
            }
        }

        String erroHash = erroStd.toString().trim()
        if (erroHash && !erroHash.contains('Warning')) {
            println ">> ERRO: Aviso SSH (Hash): ${erroHash}"
        }
        // Compara os arquivos
        List<Map> arqsMap = []
        List<String> caminhosLocais = []
        baseLocaldir.eachFileRecurse(groovy.io.FileType.FILES) { File arquivo ->
            // Pega o caminho relativo do arquivo em relação à 'lib' e converte pra padrão Linux '/'
            String caminhoRel = baseLocaldir.toPath().relativize(arquivo.toPath()).toString()
            caminhoRel = caminhoRel.replace(File.separator, '/')
            if (!caminhoRel.contains('/')) { caminhoRel = appJar } // sem versão
            // Calcula o Hash MD5 local
            caminhosLocais << caminhoRel
            java.security.MessageDigest md = java.security.MessageDigest.getInstance('MD5')
            arquivo.eachByte(8192) { byte[] buffer, Integer len -> md.update(buffer, 0, len) }
            // Se o hash remoto for diferente do local ou o arquivo não existir, vai para a lista
            if (hashesMap[caminhoRel] != md.digest().encodeHex().toString()) {
                arqsMap << [arq: arquivo, dir: caminhoRel]
            }
        }
        // Descobre o que tem no as versões antigas do servidor
        List<String> deletarArqs = []
        List<String> manterArqs = [
            appJar
        ]
        hashesMap.keySet().each { String caminhoRemoto ->
            if (!caminhosLocais.contains(caminhoRemoto) && !manterArqs.contains(caminhoRemoto)) {
                deletarArqs << caminhoRemoto
            }
        }
        // Sobe os arquivos
        println ">> INFO: ${hashesMap.size()} arquivos no servidor."
        // Deleta arquivos velhos
        if (!deletarArqs.isEmpty()) {
            println ">> INFO: Encontrados ${deletarArqs.size()} arquivos antigos. Limpando..."
            // Monta os caminhos absolutos protegidos por aspas
            Process processoRemove = [
                'ssh', '-o', 'BatchMode=yes', '-o', 'StrictHostKeyChecking=no', "${dono}@${sede}", 
                "rm -f ${deletarArqs.collect { "\'${dir}/${it}\'" }.join(' ')}"
            ].execute()
            processoRemove.waitForProcessOutput(System.out, System.err)
            
            if (processoRemove.exitValue() != 0) {
                println '>> AVISO: Não foi possível deletar arquivos antigos. Veja as permissões.'
            } else {
                deletarArqs.each { println ">> INFO [DELETADO] -> ${it}" }
            }
        }

        if (arqsMap.isEmpty()) {
            println '>> INFO: Nenhum arquivo foi modificado. Servidor já está 100% atualizado!'
        } else {
            println ">> INFO: ${arqsMap.size()} alterações. Começando transferências..."
            // Garante que a pasta base existe no servidor
            Process processoMkdir = [
                'ssh', '-o', 'StrictHostKeyChecking=no', "${dono}@${sede}", "mkdir -p ${dir}/lib"
            ].execute()
            processoMkdir.waitForProcessOutput(System.out, System.err)
            // Faz o SCP pra cada arquivo
            arqsMap.each { Map mapa ->
                println ">> INFO: Enviando -> ${mapa.dir} (${mapa.arq.length() / 1024} KB)"

                Process procScp = [
                    'scp', '-o', 'StrictHostKeyChecking=no', 
                    mapa.arq.absolutePath, 
                    "${dono}@${sede}:${dir}/${mapa.dir}"
                ].execute()
                // Saída padrão/erro do SCP direto no terminal
                procScp.waitForProcessOutput(System.out, System.err)
                
                if (procScp.exitValue() != 0) {
                    throw new GradleException("Falha ao transferir: ${mapa.dir}")
                }
            }
        }

        if (servico) {
            println ">> INFO: Reiniciando o serviço '${servico}' no servidor..."
            Process processoReinicio = [
                'ssh', '-o', 'StrictHostKeyChecking=no', "${dono}@${sede}", 
                "systemctl restart ${servico}" 
            ].execute()
            processoReinicio.waitForProcessOutput(System.out, System.err)
            
            if (processoReinicio.exitValue() != 0) {
                throw new GradleException("Falha ao reiniciar o serviço ${servico}.")
            } else {
                println ">> INFO: Fim do Deploy e serviço reiniciado!"
            }
        }
    }
}
// Biblioteras para serem usadas no código
// dependencies {}