// Declaração dos plugins
// plugins {}
// Atalhos para libs.versions.toml para facilitar a leitura
XcConfig xcConfig = project.extensions.create('xcConfig', XcConfig)
// Definição de provedores para acesso à valores de configuração e diretórios
Provider<Map<String, String>> propsProv = providers.of(LeitorProps) { 
    parameters.propertiesFile = rootProject.layout.projectDirectory.file(
        providers.gradleProperty('localPropertiesNome')
    )
}
xcConfig.projDir.convention(project.layout.projectDirectory)
xcConfig.srcDir.convention(xcConfig.projDir.map { it.dir(XcConfig.MAIN_DIR) })
xcConfig.nomeApp.convention(providers.gradleProperty('projNome'))
xcConfig.buildXDir.convention(providers.gradleProperty('buildDirXcode'))
xcConfig.macDono.convention(propsProv.map { it.get('mac.dono') })
xcConfig.macSede.convention(propsProv.map { it.get('mac.sede') })
xcConfig.macDir.convention(propsProv.map { it.get('mac.dir') })
xcConfig.vmDir.convention(xcConfig.macDir.zip(xcConfig.nomeApp) { String dir, String app ->
    new File(dir, app).path.replace(File.separator, '/')
})
xcConfig.vmAppDir.convention(xcConfig.vmDir.map {
    new File(it, 'app').path.replace(File.separator, '/')
})
xcConfig.eMac.convention(providers.systemProperty('os.name').map { 
    it.toLowerCase().contains('mac') 
})
xcConfig.xcIdPacoteApp.convention(providers.gradleProperty('appIdPacote').zip(xcConfig.nomeApp){
    String id, String app -> "${id}.${app.toLowerCase()}" 
})
xcConfig.idTime.convention(propsProv.map { it.getOrDefault('apple.idTime', 'TAPABURACO') })
xcConfig.xcodeProj.convention(xcConfig.nomeApp.map { "${it}.xcodeproj" })
xcConfig.testeUnitNome.convention(providers.gradleProperty('swiftTestDirUnit'))
xcConfig.testeUiNome.convention(providers.gradleProperty('swiftTestDirUI'))
// Biblioteras para serem usadas no código
// dependencies {}