// Declaração dos plugins
// plugins {}
// Define o diretório de build usando o nome dinâmico da pasta
project.layout.buildDirectory.set(project.layout.dir(
    providers.gradleProperty('buildDirWeb').map { new File(project.rootDir, it) }
))
// Configurações do Spring e exclusão de bibliotecas padrão
project.configurations {
    // Remove o todas as dependências de uma vez
    all {
        // exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
        exclude group: 'org.hibernate.validator', module: 'hibernate-validator'
        exclude group: 'org.yaml', module: 'snakeyaml'
        exclude group: 'org.apache.tomcat.embed', module: 'tomcat-embed-websocket'
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-jackson'
        exclude group: 'com.fasterxml.jackson.core'
        exclude group: 'tools.jackson.core'
        exclude group: 'org.springframework.boot', module: 'spring-boot-jarmode-tools'
        exclude group: 'org.apache.tomcat.embed', module: 'tomcat-embed-el'
        exclude group: 'jakarta.xml.bind', module: 'jakarta.xml.bind-api'
        exclude group: 'org.glassfish.jaxb', module: 'jaxb-runtime'
        exclude group: 'com.vaadin.external.google', module: 'android-json'
    }
}
// Configuração das fontes de recursos, bibliotecas e arquivos
project.sourceSets {
    main {
        resources {
            srcDirs += ['src/main/resources'] // mantém os recursos padrões
            // inclui o conteúdo da pasta espolio no Classpath
            srcDirs += [project.layout.dir(providers.gradleProperty(
                'espolioDir').orElse('espolio').map { new File(project.rootDir, it) }
            )]
        }
    }
}
// Manipulação do arquivo .classpath para o VSCODE parar de reclamar
project.tasks.register('posBuildWeb') {
    group = 'webActions'
    description = 'Sobrescreve o .classpath do VS Code incluindo dependências do projeto Web'
    mustRunAfter tasks.named('classes') // roda logo após a compilação do Java
    // Pega as dependências de compilação do Java
    Provider<Set<FileSystemLocation>> compDepProv = configurations.named(
        'compileClasspath'
    ).flatMap { it.elements }
    Provider<RegularFile> classpathArqProv = project.providers.provider { 
        project.layout.projectDirectory.file('.classpath') 
    }

    inputs.files(compDepProv)
    inputs.file(classpathArqProv).optional()

    doLast {
        File classpathArq = classpathArqProv.get().asFile

        if (classpathArq.exists() && classpathArq.canWrite()) {
            String xmlArq = classpathArq.text
            StringBuilder novasBib = new StringBuilder()
            
            List<String> linhasLimpas = []
            xmlArq.eachLine { String linha ->
                if (linha.contains('kind=\"lib\"')) {
                    java.util.regex.Matcher matcher = (linha =~ /path="([^"]+)"/)
                    if (matcher.find()) {
                        File arquivoNoDisco = new File(matcher.group(1))
                        if (arquivoNoDisco.exists()) { linhasLimpas << linha }
                    } else { linhasLimpas << linha }
                } else { linhasLimpas << linha }
            }
            xmlArq = linhasLimpas.join('\n')

            compDepProv.get().each { File arq ->
                String caminho = arq.asFile.absolutePath.replace(File.separator, '/')
                if (caminho.endsWith('.jar') && !xmlArq.contains("path=\"${caminho}\"")) {
                    novasBib.append("    <classpathentry kind=\"lib\" path=\"${caminho}\"/>\n")
                }
            }

            if (novasBib.length() > 0 || xmlArq != classpathArq.text) {
                if (novasBib.length() > 0) {
                    xmlArq = xmlArq.replace('</classpath>', "${novasBib.toString()}</classpath>")
                }
                classpathArq.text = xmlArq
                println ">> INFO: .classpath de ${providers.gradleProperty('projNome')} atualizado."
            }
        }
    }
}
// Exclui duplicatas
tasks.named('processResources') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
// Garanta que a tarefa de JAR também ignore duplicatas
tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
// Biblioteras para serem usadas no código
// dependencies {}