// Declaração dos plugins
// plugins {}
plugins.apply(libs.plugins.xcodeProj.get().getPluginId()) // cria Xcode projs básicos e limitados
plugins.apply(libs.plugins.buildLogicXcodeGeral.get().getPluginId()) // configurações gerais
plugins.apply(libs.plugins.buildLogicXcodeActions.get().getPluginId()) // ações de build
// Atalhos para libs.versions.toml para facilitar a leitura
Object x = project.ext.xcodeVars
// Definição de provedores para acesso à valores de configuração e diretórios
Provider<String> espNomeProv = providers.gradleProperty('espolioDir').orElse('espolio')
Provider<Directory> xcassetsDirProv = project.providers.provider { 
    project.rootProject.layout.projectDirectory.dir(
        "${x.provs.buildXDirProv.get()}/generated/Assets.xcassets"
)}
Provider<Directory> espolioDirProv = project.rootProject.layout.projectDirectory.dir(espNomeProv)
Provider<Directory> xcProjDirProv = x.provs.projDirProv.zip(x.provs.xcodeProjProv) { 
    Directory pDir, String caminho -> pDir.dir(caminho) // /app/app.xcodeproj
}
// Busca a versão swift instalada na VM
Closure<String> pegaVersaoSwift = {
    try {
        ByteArrayOutputStream saidaStd = new ByteArrayOutputStream()
        ByteArrayOutputStream erroStd = new ByteArrayOutputStream()
        Process processo = x.auxs.comandoRemoto(['swift', '--version']).execute()
        processo.waitForProcessOutput(saidaStd, erroStd)
        String saida = saidaStd.toString('UTF-8').trim()
        String erro = erroStd.toString('UTF-8').trim()
        java.util.regex.Matcher versao = (saida =~ /Swift version (\d+(?:\.\d+)*)/)

        if (!erro.isEmpty() && !erro.contains('swift-driver version:')) { 
            println ">> ERRO: falha ao extrair versão Swift: ${erro}" 
        }
        if (versao.find()) { return versao.group(1) }
    } catch (Exception e) { println ">> AVISO: versão Swift ausente. Usando padrão. ${e.message}" }
    return x.auxs.ver.swift.get() 
}
// Gera um UUID aleatório de 24 caracteres, diferente em cada geração, para builds limpas
Closure<String> criaUuid = {
    java.util.UUID.randomUUID().toString().replace('-', '').substring(0, 24).toUpperCase() 
}
// Pega um UUID existente do mapa uuids ou cria um novo se não existir
Closure<String> pegaUuid = { Map uuidsMap, String... dir -> return dir[0..-2].inject(uuidsMap) { 
    Map map, String key -> map.get(key, [:]) }.get(dir[-1], criaUuid()) 
}
// Pega ou cria uma lista de seções dentro do mapa ePBX
Closure<List<String>> pegaLista = { Map map, String nome -> return map.computeIfAbsent(nome) {[]} }
// Substitui a lógica de mapa e default.value
Closure<String> pegaExtensao = { String extensao -> String chave = extensao.toLowerCase()
    final Map<String, String> exts = [
        file: 'file.',
        gif: 'image.gif',
        jpeg: 'image.jpeg',
        jpg: 'image.jpeg',
        json: 'text.json',
        plist: 'text.plist.xml',
        png: 'image.png',
        storyboard: 'file.storyboard',
        swift: 'sourcecode.swift',
        xcassets: 'folder.assetcatalog',
        xib: 'file.xib'
    ]
    
    return exts.get(chave, "${exts['file']}${chave}")
}
// Construtor de elementos ContainerItemProxy para o .pbxproj
Closure<String> criaPBXContnrItemProxy = { Map uuidsMap, String prcId, String alvoId, String alvo ->
    return """
    ${prcId} /* PBXContainerItemProxy */ = {
        isa = PBXContainerItemProxy;
        containerPortal = ${pegaUuid(uuidsMap, 'base', 'projeto')} /* Project object */;
        proxyType = ${x.cons.proxyType};
        remoteGlobalIDString = ${alvoId};
        remoteInfo = \"${alvo}\";
    };"""
}
// Construtor de elementos FileReference para o .pbxproj
Closure<String> criaPBXFileReference = { String fileRefId, String alvo, String nome, String tipo ->
    return """
    ${fileRefId} /* ${alvo}.${tipo} */ = {
        isa = PBXFileReference;
        explicitFileType = \"wrapper.${tipo == 'app' ? 'application' : 'cfbundle'}\";
        includeInIndex = ${x.cons.includeInIndex};
        path = \"${nome}.${tipo}\";
        sourceTree = BUILT_PRODUCTS_DIR;
    };"""
}
// Construtor de elementos FrameworksBuildPhase para o .pbxproj
Closure<String> criaPBXFrameworksBuildPhase = { String frameworksBuildPhaseId, List<String> arqs -> 
    return """
    ${frameworksBuildPhaseId} = {
        isa = PBXFrameworksBuildPhase;
        buildActionMask = ${x.cons.buildActionMask};
        files = (
            ${arqs ? arqs.join(',\n').indent(12).strip() : ''}
        );
        runOnlyForDeploymentPostprocessing = ${x.cons.runOnlyForDeploymentPostprocessing};
    };"""
}
// Construtor de elementos Group para o .pbxproj
Closure<String> criaPBXGroup = { String grupoId, String nome, List<String> filhos -> return """
    ${grupoId} = { /* ${nome} */
        isa = PBXGroup;
        children = (
            ${filhos.join(',\n').indent(12).strip()}
        );
        ${nome == 'base' ? '' : 'name = ' + (nome != 'Products' ? "\"${nome}\"" : nome) + ';'}
        sourceTree = \"<group>\";
    };"""
}
// Construtor de elementos NativeTarget para o .pbxproj
Closure<String> criaPBXNativeTarget = { String alvoId, String nomeCompleto, String listaConfigId, 
    List<String> fasesIds, List<String> depIds, String nome, String fileRefId, String tipo -> 
    String ids = String.join('\n', 'dependencies = (', depIds.join('\n').indent(12))
    String ext = tipo.contains('app') ? 'app' : (tipo.contains('test') ? 'xctest' : 'unknown')
    return """
    ${alvoId} /* ${nomeCompleto} */ = {
        isa = PBXNativeTarget;
        buildConfigurationList = ${listaConfigId} /* Lista para configurar \"${nomeCompleto}\" */;
        buildPhases = (
            ${fasesIds ? fasesIds.join(',\n').indent(12).strip() : ''}
        );
        ${tipo != 'application' ? ids.strip() + '\n);'.indent(8) : ''}
        name = \"${nomeCompleto}\";
        productName = \"${nome}\";
        productReference = ${fileRefId} /* ${nomeCompleto}.${ext} */;
        productType = \"com.apple.product-type.${tipo}\";
    };"""
}
// Construtor de elementos TargetDependency para o .pbxproj
Closure<String> criaPBXTargetDependency = { String depId, String alvoId, String alvo, 
    String prcAlvo -> return """
    ${depId} /* PBXTargetDependency */ = {
        isa = PBXTargetDependency;
        target = ${alvoId} /* ${alvo} */;
        ${prcAlvo != null ? "targetProxy = ${prcAlvo};" : ''}
    };"""
}
// Construtor de elementos SourcesBuildPhase para o .pbxproj
Closure<String> criaPBXSourcesBuildPhase = { String faseId, List<String> ids -> return """
    ${faseId} = {
        isa = PBXSourcesBuildPhase;
        buildActionMask = ${x.cons.buildActionMask};
        files = (
            ${ids.join(',\n').indent(12).strip()}
        );
        runOnlyForDeploymentPostprocessing = ${x.cons.runOnlyForDeploymentPostprocessing};
    };"""
}
// Construtor de elementos ResourcesBuildPhase para o .pbxproj
Closure<String> criaPBXResourcesBuildPhase = { String faseArqsId, List<String> refsIds -> return """
    ${faseArqsId} = {
        isa = PBXResourcesBuildPhase;
        buildActionMask = ${x.cons.buildActionMask};
        files = (${refsIds ? '\n' + refsIds.join(',\n').indent(12) + '\n);'.indent(8) : ');'}
        runOnlyForDeploymentPostprocessing = ${x.cons.runOnlyForDeploymentPostprocessing};
    };"""
}
// Construtores de elementos de Build Settings
Closure<String> configuraBuild = { String nome, String alvo, String tipo, String config,
    String idPacote, String nomeApp, String verSwift, String plataforma ->
    String testeTipo = alvo ? (tipo.contains('ui') ? 'UI' : '') : null
    String buildXDir = x.provs.buildXDirProv.get()
    String comum = """
        ENABLE_APP_INTENTS_METADATA_EXTRACTION = NO;
        GENERATE_INFOPLIST_FILE = YES;
        SWIFT_VERSION = \"${verSwift}\";
        ${config == 'Debug' ? 'ENABLE_TESTABILITY = YES;' : ''}"""
    String comumApp = comum + """
        PRODUCT_BUNDLE_IDENTIFIER = \"${idPacote}.${plataforma}\";
        INFOPLIST_KEY_CFBundleShortVersionString = \"${x.provs.versaoNumeroProv.get()}\";
        INFOPLIST_KEY_CFBundleVersion = \"${x.provs.versaoNumeroProv.get()}\";
        INFOPLIST_KEY_UIApplicationSceneManifest_EnableMultipleWindows = NO;
        PRODUCT_NAME = \"${nomeApp}\";
        PRODUCT_MODULE_NAME = \"${nomeApp}\";
        ASSETCATALOG_COMPILER_APPICON_NAME = \"AppIcon\";"""
    String comumTeste = comum + """
        PRODUCT_BUNDLE_IDENTIFIER = \"${idPacote}.${testeTipo}Tests.${plataforma}\";
        PRODUCT_NAME = \"${nome}\";
        TEST_TARGET_NAME = \"${alvo}\";
        ${testeTipo == 'UI' ? 'USES_XCTRUNNER = YES;' : 'BUNDLE_LOADER = \"\$(TEST_HOST)\";'}
        ${plataforma == 'ios' ? 'TARGETED_DEVICE_FAMILY = \"1,2\";' : ''}"""
    String comumIos = """
        IPHONEOS_DEPLOYMENT_TARGET = \"${x.auxs.ver.minIosVer.get()}\";
        SDKROOT = \"${(tipo == 'appios' && config == 'Release') ? 'iphoneos' : 'iphonesimulator'}\";
        SUPPORTED_PLATFORMS = \"iphonesimulator iphoneos\";"""
    String comumMacos = """
        MACOSX_DEPLOYMENT_TARGET = \"${x.auxs.ver.minMacosVer.get()}\";
        SDKROOT = \"macosx\"; 
        SUPPORTED_PLATFORMS = \"macosx\";"""
    
    switch (tipo) {
        case 'main': return """
            ALWAYS_SEARCH_USER_PATHS = NO;
            SYMROOT = \"\$(PROJECT_DIR)/../${buildXDir}/products\";
            OBJROOT = \"\$(PROJECT_DIR)/../${buildXDir}/intermediates\";
            SHARED_PRECOMPS_DIR = \"\$(OBJROOT)/PrecompiledHeaders\";
            CONFIGURATION_BUILD_DIR = \"\$(SYMROOT)/\$(CONFIGURATION)-\$(PLATFORM_NAME)\";"""
            break
        case 'appios': return (comumApp + comumIos).indent(4)            
            break
        case 'appmacos': return (comumApp + comumMacos).indent(4) + """
            COMBINE_HIDPI_IMAGES = YES;"""
            break
        case 'unitios': return (comumTeste + comumIos).indent(4) + """
            TEST_HOST = \"\$(BUILT_PRODUCTS_DIR)/${nomeApp}.app/${nomeApp}\";"""
            break
        case 'unitmacos': return (comumTeste + comumMacos).indent(4) + """
            TEST_HOST = \"\$(BUILT_PRODUCTS_DIR)/${nomeApp}.app/Contents/MacOS/${nomeApp}\";"""
            break
        case 'uiios': return (comumTeste + comumIos).indent(4) + """
            PROVISIONING_PROFILE = \"\";"""
            break
        case 'uimacos': return (comumTeste + comumMacos).indent(4)
            break
        default: return ''
    }
}
// Construtor de elementos BuildConfiguration para o .pbxproj
Closure<String> criaXCBuildConfiguration = { String configId, String nome, String alvo, String tipo, 
    String config, String pacote, String proj, String verSwift, String plataforma -> return """
    ${configId} = {
        isa = XCBuildConfiguration;
        buildSettings = {
            ${configuraBuild(nome, alvo, tipo, config, pacote, proj, verSwift, plataforma)}
        };
        name = \"${config}\";
    };"""
}
// Construtor de elementos ConfigurationList para o .pbxproj
Closure<String> criaXCConfigurationList = { String listaConfigId, List<String> configsBuilds, 
    String config -> return """
    ${listaConfigId} = {
        isa = XCConfigurationList;
        buildConfigurations = (
            ${configsBuilds.join(',\n').indent(12).strip()}
        );
        defaultConfigurationIsVisible = ${x.cons.defaultConfigurationIsVisible};
        defaultConfigurationName = \"${config}\";
    };"""
}
// Construtor de elementos FileReference para o .pbxproj
Closure<String> criaFileReference = { String arqRefId, String nomeArq, String caminho, 
    String tipoArq -> return """
    ${arqRefId} /* ${nomeArq} */ = {
        isa = PBXFileReference;
        lastKnownFileType = \"${tipoArq}\";
        path = \"${caminho}\";
        sourceTree = \"<group>\";
    };"""
}
// Construtor de elementos BuildFile para o .pbxproj
Closure<String> criaBuildFile = { String buildRefId, String nomeArq, String arqRefId -> return """
    ${buildRefId} /* ${nomeArq} in Sources */ = {
        isa = PBXBuildFile;
        fileRef = ${arqRefId} /* ${nomeArq} */;
    };"""
}
// Centraliza File Reference e BuildFile para evitar repetição
Closure<Map<String, String>> processaArqRefs = { Map uuidsMap, Map ePBXMap, String rastro ->
    String caminho = rastro.replace(File.separator, '/')
    String nomeExib = rastro.contains('/') ? rastro.substring(rastro.lastIndexOf('/') + 1) : rastro
    String ref = pegaUuid(uuidsMap, 'fileRef', rastro) 
    String buildRef = pegaUuid(uuidsMap,'buildRef', rastro)
    String ext = nomeExib.contains('.') ? nomeExib.substring(nomeExib.lastIndexOf('.') + 1) : ''
    String tipoArq = pegaExtensao(ext)

    pegaLista(ePBXMap, 'FileReference') << criaFileReference(ref, nomeExib, caminho, tipoArq)
    pegaLista(ePBXMap, 'PBXBuildFile') << criaBuildFile(buildRef, nomeExib, ref)

    return [nome: nomeExib, caminho: caminho, ref: ref, buildRef: buildRef]
}
// Cria e agrega seções do arquivo PBXproj
Closure<String> criaBlocoPBX = { Map ePBXMap, List<String> nomes, String junta -> return """\n
    /* Begin ${nomes[0]} section */
    ${nomes.collect { String nome -> pegaLista(ePBXMap, nome).join(junta) }.join(junta).strip()}
    /* End ${nomes[0]} section */\n\n""".indent(12)
}
// Criar uma seção <BuildableReference> para os schemes
Closure<String> criaRefXML = { Map<String, String> refMap, Boolean eApp, String proj -> return """
        <BuildableReference
            BuildableIdentifier=\"primary\"
            BlueprintIdentifier=\"${refMap.id}\"
            BuildableName=\"${refMap.nome + (eApp ? '.app' : '.xctest')}\"
            BlueprintName=\"${refMap.diagrama}\"
            ReferencedContainer=\"container:${proj}\">
        </BuildableReference>""".strip()
}
// Função unificada para criar cada scheme
Closure<String> criaScheme = { Map alvoMap, List testaveis, Map alvoSedeMap = null, String proj ->
    boolean eScheme = (alvoSedeMap == null)
    String baseRefXml = criaRefXML(alvoMap, eScheme, proj)
    String sedeRefXml = alvoSedeMap ? criaRefXML(alvoSedeMap, true, proj) : ''
    // Define o <BuildableReference> para Launch/Profile
    String rodavelRefXml = eScheme ? baseRefXml : sedeRefXml
    String buildArqAttr = eScheme ? '\nbuildArchitectures = \"Automatic\"'.indent(24)[0..-2] : ''
    // Cria as <BuildActionEntries>
    StringWriter entradasAcao = new StringWriter()
    if (eScheme) { // Apenas o App
        entradasAcao << """
            <BuildActionEntry 
                buildForTesting=\"NO\"
                buildForRunning=\"YES\"
                buildForProfiling=\"YES\"
                buildForArchiving=\"YES\"
                buildForAnalyzing=\"YES\">
                ${baseRefXml.indent(8).strip()}
            </BuildActionEntry>"""
    } else { // Bundle de Teste
        entradasAcao << """
            <BuildActionEntry 
                buildForTesting=\"YES\"
                buildForRunning=\"YES\"
                buildForProfiling=\"NO\"
                buildForArchiving=\"NO\"
                buildForAnalyzing=\"YES\">
                ${baseRefXml.indent(8).strip()}
            </BuildActionEntry>"""
        // App Host
        entradasAcao << """\n
            <BuildActionEntry 
                buildForTesting=\"YES\"
                buildForRunning=\"YES\"
                buildForProfiling=\"YES\"
                buildForArchiving=\"YES\"
                buildForAnalyzing=\"YES\">
                ${sedeRefXml.indent(8).strip()}
            </BuildActionEntry>"""
    }
    // Cria as <Testables>
    String entradasTeste = testaveis.collect { Map<String, String> testavel ->
        String testeRefXml = criaRefXML(testavel, false, proj)
        """
        <TestableReference 
            skipped=\"NO\">
            ${testeRefXml.indent(4).strip()}
        </TestableReference>"""
    }.join('\n')
    // O Template xml Principal
    return """\
        <?xml version=\"1.0\" encoding=\"UTF-8\"?>
        <Scheme
            LastUpgradeVersion=\"${x.auxs.ver.schemeUpgradeVersion.get()}\"
            version=\"${x.auxs.ver.schemeVersion.get()}\">
            <BuildAction
                parallelizeBuildables=\"YES\"
                buildImplicitDependencies=\"YES\"${buildArqAttr}>
                <BuildActionEntries>
                    ${entradasAcao.toString().indent(8).strip()}
                </BuildActionEntries>
            </BuildAction>
            <TestAction
                buildConfiguration=\"Debug\"
                selectedDebuggerIdentifier=\"Xcode.DebuggerFoundation.Debugger.LLDB\"
                selectedLauncherIdentifier=\"Xcode.DebuggerFoundation.Launcher.LLDB\"
                shouldUseLaunchSchemeArgsEnv=\"YES\"
                shouldAutocreateTestPlan=\"YES\">
                <Testables>
                    ${entradasTeste.indent(12)}
                </Testables>
            </TestAction>
            <LaunchAction
                buildConfiguration=\"Debug\"
                selectedDebuggerIdentifier=\"Xcode.DebuggerFoundation.Debugger.LLDB\"
                selectedLauncherIdentifier=\"Xcode.DebuggerFoundation.Launcher.LLDB\"
                launchStyle=\"0\"
                useCustomWorkingDirectory=\"NO\"
                ignoresPersistentStateOnLaunch=\"NO\"
                debugDocumentVersioning=\"YES\"
                debugServiceExtension=\"internal\"
                allowLocationSimulation=\"YES\">
                <BuildableProductRunnable
                    runnableDebuggingMode=\"0\">
                    ${rodavelRefXml.indent(12).strip()}
                </BuildableProductRunnable>
            </LaunchAction>
            <ProfileAction
                buildConfiguration=\"Release\"
                shouldUseLaunchSchemeArgsEnv=\"YES\"
                savedToolIdentifier=\"\"
                useCustomWorkingDirectory=\"NO\"
                debugDocumentVersioning=\"YES\">
                <BuildableProductRunnable
                    runnableDebuggingMode=\"0\">
                    ${rodavelRefXml.indent(12).strip()}
                </BuildableProductRunnable>
            </ProfileAction>
            <AnalyzeAction
                buildConfiguration=\"Debug\">
            </AnalyzeAction>
            <ArchiveAction
                buildConfiguration=\"Release\"
                revealArchiveInOrganizer=\"YES\">
            </ArchiveAction>
        </Scheme>""".stripIndent().replaceAll('[\\n\\n]{1,3}', '\n')
}
// Descobre arquivos fonte e de recursos, populando listas em ePBX
Closure<Void> descobreArqs = { Map ePBXMap, File testeDir, File baseDir, File resDir, File espDir, 
    Map arqsTesteMap ->
    testeDir.eachDir { File dir ->
        String dirNome = dir.name
        if (arqsTesteMap.containsKey(dirNome)) { 
            String arqNome = arqsTesteMap[dirNome]
            dir.eachFileRecurse(groovy.io.FileType.FILES) { File arq ->
                if (arq.name.contains('.DS_Store')) { return }
                pegaLista(ePBXMap, arqNome).add(
                    x.provs.projDirProv.get().getAsFile().toURI().relativize(arq.toURI()).getPath()
                )
            }
        } else { println ">> AVISO: local de teste \'${dirNome}\' não pertence a nenhum alvo." }
    }
    // Códigos Fonte (Swift)
    if (baseDir.exists()) {
        baseDir.eachFileRecurse(groovy.io.FileType.FILES) { File arq ->
            if (arq.name.endsWith('.swift')) {
                pegaLista(ePBXMap, 'fonteArqs').add(
                    x.provs.projDirProv.get().getAsFile().toURI().relativize(arq.toURI()).getPath())
            }
        }
    }
    // Pega e categoriza todos os recursos
    Closure<Void> pegaRes
    pegaRes = { File raizArq, File arq, String alvoLista, String prefixo = '' ->
        if (!arq.exists()) return
        arq.eachFile { File dir ->
            if (dir.name.contains('.DS_Store')) return
            // Se for a pasta do Asset Catalog, adiciona ela inteira e não entra nela
            if (dir.isDirectory() && dir.name.endsWith('.xcassets')) {
                String caminhoRelativo = raizArq.toURI().relativize(dir.toURI()).getPath()
                // Tira a última barra para ficar "Assets.xcassets"
                if (caminhoRelativo.endsWith('/')) caminhoRelativo = caminhoRelativo[0..-2]
                pegaLista(ePBXMap, alvoLista).add(prefixo + caminhoRelativo)
                return
            } 
            else if (dir.isDirectory()) {
                pegaRes(raizArq, dir, alvoLista, prefixo) // recursão normal
            } 
            else {
                pegaLista(ePBXMap, alvoLista).add(
                    prefixo + raizArq.toURI().relativize(dir.toURI()).getPath()
                )
            }
        }
    }

    pegaRes(resDir, resDir, 'recursosLocal', "${x.cons.resDir}/")
    pegaRes(espDir, espDir, 'recursosExt', "../${espNomeProv.get()}/")
    // Adiciona a pasta dos ícones
    File xcassetsPaiDir = xcassetsDirProv.get().getAsFile().parentFile
    String buildXDir = x.provs.buildXDirProv.get()
    pegaRes(xcassetsPaiDir, xcassetsPaiDir, 'recursosLocal', "../${buildXDir}/generated/")
}
// Processa arquivos fonte e de recursos, criando referências PBX
Closure<Map> processaReferencias = { Map uuidsMap, Map ePBXMap, List alvos, Map arqsTesteMap ->
    List<String> cplFontes = [], gpFontes = [], cplRecursos = []
    Map<String, List<String>> cplTestsMap = alvos.collectEntries { Map alvoTesteMap ->
        String testeNomeBase = alvoTesteMap.nome.get()
        String arqNome = arqsTesteMap[testeNomeBase]
        List<String> compilas = pegaLista(ePBXMap, arqNome).collect { String dir ->
            Map<String, String> arqvMap = processaArqRefs(uuidsMap, ePBXMap, dir)
            return "${arqvMap.buildRef} /* ${new File(arqvMap.caminho).name} in Sources */" 
        }
        [(testeNomeBase): compilas]
    }
    // Processa arquivos fonte
    pegaLista(ePBXMap, 'fonteArqs').each { String arq ->
        Map<String, String> entMap = processaArqRefs(uuidsMap, ePBXMap, arq)
        cplFontes << "${entMap.buildRef} /* ${new File(entMap.caminho).name} in Sources */"
        gpFontes << "${entMap.ref} /* ${new File(entMap.caminho).name} */," 
    }
    // Processa Recursos Locais
    pegaLista(ePBXMap, 'recursosLocal').each { String arq ->
        Map<String, String> entMap = processaArqRefs(uuidsMap, ePBXMap, arq)
        cplRecursos << "${entMap.buildRef} /* ${new File(entMap.caminho).name} in Resources */"
        gpFontes << "${entMap.ref} /* ${new File(entMap.caminho).name} */," 
    }
    // Processa Recursos Externos
    pegaLista(ePBXMap, 'recursosExt').each { String arq ->
        Map<String, String> entMap = processaArqRefs(uuidsMap, ePBXMap, arq)
        cplRecursos << "${entMap.buildRef} /* ${new File(entMap.caminho).name} in Resources */"
        gpFontes << "${entMap.ref} /* ${new File(entMap.caminho).name} */," 
    }
    
    return [ fontes: cplFontes, recs: cplRecursos, groupFontes: gpFontes, testes: cplTestsMap ]
}
// Gera os alvos PBX para o projeto
Closure<Map<String, String>> criaAlvo = { Map uuidsMap, Map ePBXMap, List alvos, List os, List recs,
    Map testMap, List fontes, Map provMap, String nomeApp, String idPacote, String verSwift ->
    Map<String, String> atrbAlvosMap = [:]
    
    alvos.each { Map<String, Object> alvoMap ->
        String nomeBase = alvoMap.nome.get()
        String alvoId = alvoMap.id
        boolean eAlvoTeste = alvoMap.containsKey('sede')

        os.each { String plataforma ->
            String alvoNomeCompleto = provMap[nomeBase][plataforma].nomeAlvoProv.get()
            String nomeProd = alvoMap.nome.get()
            String ext = (alvoId == 'app' ? 'app' : 'xctest')
            String alvoUUId = pegaUuid(uuidsMap, plataforma, nomeBase, 'projeto')
            String prodArqRefId = pegaUuid(uuidsMap, plataforma, nomeBase, 'produtoRef')
            String configListaId = pegaUuid(uuidsMap, plataforma, nomeBase, 'configList')
            String faseId = pegaUuid(uuidsMap, plataforma, nomeBase, 'sourcesPhase')
            String faseEstrId = pegaUuid(uuidsMap, plataforma, nomeBase, 'frameworksPhase')
            String intentsRefId = pegaUuid(uuidsMap, plataforma, nomeBase, 'intentsRef')
            String intentsBuildId = pegaUuid(uuidsMap, plataforma, nomeBase, 'intentsBuild')
            String arqId = eAlvoTeste ? null : pegaUuid(uuidsMap, plataforma, nomeBase, 'faseArqs')
            List<String> alvoFnts = [], confgsPorLista = [], idsDependetes = [], estruturaIds = []
            List<String> idFases = [ "${faseId} /* Sources */", "${faseEstrId} /* Frameworks */" ]
            
            if (alvoId == 'app') { alvoFnts = fontes }
            else if (testMap.containsKey(nomeProd)) { alvoFnts = testMap[nomeProd] }
            
            if (arqId) {
                pegaLista(ePBXMap, 'PBXResourcesBuildPhase') << criaPBXResourcesBuildPhase(
                    arqId, recs) 
                idFases << "${arqId} /* Resources */"
            }
            
            ['Debug', 'Release'].each { String config ->
                String configId = pegaUuid(uuidsMap, plataforma, nomeBase, config.toLowerCase())
                String configPfx = alvoId ? alvoId : 'unknown'
                String pacote = "${configPfx}${plataforma.toLowerCase()}"
                String prod = (configPfx == 'app' ? nomeApp : nomeProd)
                String nome = nomeApp + (configPfx == 'app' ? '' : ('-' + plataforma))
                confgsPorLista << "${configId} /* ${config} */"
                
                pegaLista(ePBXMap, 'BuildConfiguration') << criaXCBuildConfiguration(configId, prod, 
                    nome, pacote, config, idPacote, nomeApp, verSwift, plataforma.toLowerCase())
            }
            
            if (eAlvoTeste) {
                String nomeSedeBase = alvoMap.sede.get()
                String alvoSedeId = pegaUuid(uuidsMap, plataforma, nomeSedeBase, 'projeto')
                String alvoSedeNome = provMap[nomeSedeBase][plataforma].nomeAlvoProv.get()
                String depId = pegaUuid(uuidsMap, plataforma, nomeBase, 'dependency')
                String proc = pegaUuid(uuidsMap, plataforma, nomeBase, '')
                atrbAlvosMap["\"${alvoUUId}\""] = "{ TestTargetID = \"${alvoSedeId}\"; }"
                
                if (proc) pegaLista(ePBXMap, 'PBXContainerItemProxy') << criaPBXContnrItemProxy( 
                    uuidsMap, proc, alvoSedeId, alvoSedeNome)
                
                idsDependetes << "${depId} /* PBXTargetDependency */"
                pegaLista(ePBXMap, 'PBXTargetDependency') << criaPBXTargetDependency(depId, 
                    alvoSedeId, alvoSedeNome, proc)
            }

            pegaLista(ePBXMap, 'PBXFileReference') << """
            ${intentsRefId} /* AppIntents.framework */ = {
                isa = PBXFileReference;
                lastKnownFileType = wrapper.framework;
                name = AppIntents.framework;
                path = System/Library/Frameworks/AppIntents.framework;
                sourceTree = SDKROOT;
            };""".indent(-8)

            pegaLista(ePBXMap, 'PBXBuildFile') << """
            ${intentsBuildId} /* AppIntents.framework in Frameworks */ = {
                isa = PBXBuildFile;
                fileRef = ${intentsRefId} /* AppIntents.framework */;
                settings = {ATTRIBUTES = (Weak, ); }; 
            };""".indent(-8)

            estruturaIds << "${intentsBuildId} /* AppIntents.framework in Frameworks */"
            
            pegaLista(ePBXMap, 'projectTargets') << "${alvoUUId} /* ${alvoNomeCompleto} */"
            pegaLista(ePBXMap, 'productsGpChildren') << "${prodArqRefId} /* ${nomeProd}.${ext} */,"
            pegaLista(ePBXMap, 'PBXFileReference') << criaPBXFileReference(prodArqRefId, 
                alvoNomeCompleto, nomeProd, ext)
            pegaLista(ePBXMap, 'PBXFrameworksBuildPhase') << criaPBXFrameworksBuildPhase(faseEstrId, 
                estruturaIds)
            pegaLista(ePBXMap, 'PBXSourcesBuildPhase') << criaPBXSourcesBuildPhase(faseId, alvoFnts)
            pegaLista(ePBXMap, 'ConfigurationList') << criaXCConfigurationList(configListaId, 
                confgsPorLista, (alvoId == 'app' ? 'Release' : 'Debug'))
            pegaLista(ePBXMap, 'PBXNativeTarget') << criaPBXNativeTarget(alvoUUId, alvoNomeCompleto, 
                configListaId, idFases, idsDependetes, nomeProd, prodArqRefId, alvoMap.tipo)
        }
    }
    return atrbAlvosMap // retorna o mapa populado
}
// Gera a estrutura base do projeto PBX
Closure<Void> criaProjetoBasePBX = { Map uuidsMap, Map ePBXMap, Map atrbAlvosMap, List gpFontes, 
    String nomeApp, String idPacote, String verSwift, String xcodeProjDir ->
    ['Debug', 'Release'].each { String config -> 
        pegaLista(ePBXMap, 'XCBuildConfiguration') << criaXCBuildConfiguration(pegaUuid(uuidsMap, 
            'base', config), null, null, 'main', config, idPacote, nomeApp, verSwift, null) 
    }
    
    pegaLista(ePBXMap, 'PBXGroup') << criaPBXGroup( pegaUuid(uuidsMap, 'base', 'mainGroup'), 'base', 
        [pegaUuid(uuidsMap, 'base', 'gpFontes'), pegaUuid(uuidsMap, 'base', 'gpTestes'), 
        pegaUuid(uuidsMap, 'base', 'gpProduto')])
    pegaLista(ePBXMap, 'PBXGroup') << criaPBXGroup( pegaUuid(uuidsMap, 'base', 'gpProduto'), 
        'Products', pegaLista(ePBXMap, 'productsGpChildren'))
    pegaLista(ePBXMap, 'PBXGroup') << criaPBXGroup(
        pegaUuid(uuidsMap, 'base', 'gpFontes'), x.provs.appDir.get(), gpFontes)
    List<String> testeFilhos = []
    ePBXMap.findAll { String idx, List<String> elementos -> idx.endsWith('Files') }.each { 
        String inx, List<String> listaArqs ->
        listaArqs.each { String arq -> 
            String ref = pegaUuid(uuidsMap, 'fileRef', arq)
            testeFilhos << "${ref} /* ${new File(arq).name} */,"
        }
    }
    pegaLista(ePBXMap, 'PBXGroup') << criaPBXGroup(pegaUuid(uuidsMap, 'base', 'gpTestes'), 
        'test', testeFilhos)
    pegaLista(ePBXMap, 'XCConfigurationList') << criaXCConfigurationList(
        pegaUuid(uuidsMap, 'base', 'projectConfigList'), 
        [ pegaUuid(uuidsMap, 'base', 'Debug') + ' /* Debug */', 
        pegaUuid(uuidsMap, 'base', 'Release') + ' /* Release */'], 'Debug')
    pegaLista(ePBXMap, 'PBXProject') << """
        ${pegaUuid(uuidsMap, 'base', 'projeto')} = {
            isa = PBXProject;
            attributes = {
                TargetAttributes = { 
                    ${atrbAlvosMap.collect { 
                        String idx, String elemento -> "\n${idx} = ${elemento};\n" 
                    }.join('\n').indent(20).strip()}
                };
            };
            buildConfigurationList = ${pegaUuid(uuidsMap, 'base', 'projectConfigList') + 
                "; /* Build configuration list for PBXProject \"${xcodeProjDir}\" */"}
            mainGroup = ${pegaUuid(uuidsMap, 'base', 'mainGroup')};
            productRefGroup = ${pegaUuid(uuidsMap, 'base', 'gpProduto')};
            targets = (
                ${pegaLista(ePBXMap, 'projectTargets').join(',\n').indent(16).strip()}
            );
        };""".indent(-4)
}
// Escreve o arquivo project.pbxproj e os schemes
Closure<Void> escreveArquivosFinais = { Map uuidsMap, Map ePBXMap, Map provsMap, File pbxArq, 
    File schemesDir, List plataformas, Map appAlvosMap, List testeAlvos, String xcodeProjDir ->
    pbxArq.text = """\
        // !\$*UTF8*\$!
        {
            archiveVersion = ${x.auxs.ver.archiveVersion.get()};
            classes = {};
            objectVersion = ${x.auxs.ver.objectVersion.get()};
            objects = {
                ${criaBlocoPBX(ePBXMap,['PBXBuildFile'],'')}
                ${criaBlocoPBX(ePBXMap,['PBXContainerItemProxy'],'\n')}
                ${criaBlocoPBX(ePBXMap,['PBXFileReference','FileReference'],'\n')}
                ${criaBlocoPBX(ePBXMap,['PBXFrameworksBuildPhase'],'\n')}
                ${criaBlocoPBX(ePBXMap,['PBXGroup'],'\n')}
                ${criaBlocoPBX(ePBXMap,['PBXNativeTarget'],'\n')}
                ${criaBlocoPBX(ePBXMap,['PBXTargetDependency'],'\n')}
                ${criaBlocoPBX(ePBXMap,['PBXProject'],'')}
                ${criaBlocoPBX(ePBXMap,['PBXSourcesBuildPhase'],'\n')}
                ${criaBlocoPBX(ePBXMap,['PBXResourcesBuildPhase'],'\n')}
                ${criaBlocoPBX(ePBXMap,['XCBuildConfiguration','BuildConfiguration'],'\n')}
                ${criaBlocoPBX(ePBXMap,['XCConfigurationList','ConfigurationList'],'\n')}
            };
            rootObject = ${pegaUuid(uuidsMap, 'base', 'projeto')};
        }""".stripIndent().replaceAll('[\\n\\n]{1,3}', '\n').replaceAll(',,', ',').replaceAll(
            "../${espNomeProv.get()}", x.cons.resDir).replaceAll(/,\n\s*\);/, '\n\t\t\t);')
    
    plataformas.each { String plataforma ->
        String nomeBase = appAlvosMap.nome.get()
        String alvoNome = provsMap[nomeBase][plataforma].nomeAlvoProv.get()
        String alvoBaseId = pegaUuid(uuidsMap, plataforma, nomeBase, 'projeto')
        Map<String, String> alvoSedeMap = [ id: alvoBaseId, nome: alvoNome, diagrama: alvoNome ]
        List<Map<String, String>> appTestaveis = testeAlvos.collect { Map alvoTesteMap ->
            String testeNomeBase = alvoTesteMap.nome.get()
            Map<String, Provider<String>> alvoTestMap = provsMap[testeNomeBase][plataforma]
            return [
                id: pegaUuid(uuidsMap, plataforma, testeNomeBase, 'projeto'),
                nome: alvoTestMap.nomeProdProv.get(),
                diagrama: alvoTestMap.nomeAlvoProv.get()
            ]
        }

        new File(schemesDir, "${alvoNome}.xcscheme").text = criaScheme(
            alvoSedeMap, appTestaveis, null, xcodeProjDir)
        
        appTestaveis.each { Map testavel ->
            new File(schemesDir, "${testavel.diagrama}.xcscheme").text = criaScheme(
                testavel, [testavel], alvoSedeMap, xcodeProjDir)
        }
        // .plist para export
        new File(pbxArq.parentFile, 'exportOptions.plist').text = """
            <?xml version=\"1.0\" encoding=\"UTF-8\"?>
            <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\">
            <plist version=\"1.0\">
                <dict>
                    <key>method</key>
                    <string>${x.provs.metodoProv.get()}</string>
                    <key>signingStyle</key>
                    <string>automatic</string>
                    <key>stripSwiftSymbols</key>
                    <true/>
                    <key>teamID</key>
                    <string>${x.provs.idTimeProv.get()}</string>
                    <key>provisioningProfiles</key>
                    <dict>
                        <key>${x.provs.xcIdPacoteAppProv.get()}</key>
                        <string>AppStore_${x.provs.xcIdPacoteAppProv.get()}</string>
                    </dict>
                    <key>iCloudContainerEnvironment</key>
                    <string>Production</string>
                </dict>
            </plist>""".stripIndent()
    }
}
// Lê o sistema de arquivos, popula os mapas globais e monta os arquivos para o xcode
tasks.register('xproj') {
    description = 'Gera os arquivos do projeto .xcodeproj'
    group = 'Xcode Actions'

    Provider<Directory> xcSchemesDirProv = xcProjDirProv.map { it.dir('xcshareddata/xcschemes') }
    Provider<Directory> resourcesDirProv = x.provs.projDirProv.map { it.dir(x.cons.resDir) }
    Provider<Directory> srcTestSwiftDirProv = x.provs.projDirProv.map { it.dir(x.cons.testeDir) }
    Provider<RegularFile> xcPBXProjArqProv = xcProjDirProv.map { it.file('project.pbxproj') }

    inputs.files(tasks.named('xIcone'))
    inputs.dir x.provs.srcDirProv
    inputs.dir srcTestSwiftDirProv
    inputs.dir(resourcesDirProv).optional()
    inputs.dir(espolioDirProv).optional()
    outputs.dir xcProjDirProv

    doFirst {
        File xcProjDir = xcProjDirProv.get().getAsFile()
        if (xcProjDir.exists()) { xcProjDir.deleteDir() }
        xcProjDir.mkdirs()
        xcSchemesDirProv.get().asFile.mkdirs()
    }

    doLast {
        // Variáveis e resolução de provedores
        String nomeApp = x.provs.nomeAppProv.get()
        String idPacote = x.provs.xcIdPacoteAppProv.get()
        String verSwift = pegaVersaoSwift()
        String xcodeProjDir = x.provs.xcodeProjProv.get()
        List<String> plataformas = ['iOS', 'macOS']
        Map<String, Object> appAlvosMap = [ 
            nome: x.provs.nomeAppProv, tipo: 'application', id: 'app' 
        ]
        List<Map<String, Object>> testAlvos = [ // Lista de alvos de teste
            [ 
                nome: x.provs.testeUnitNomeProv, tipo: 'bundle.unit-test', sede: x.provs.nomeAppProv, 
                id: 'unit', arqs: x.provs.testeUnitNomeProv.map { "${it}Files" } 
            ], [ 
                nome: x.provs.testeUiNomeProv, tipo: 'bundle.ui-testing', sede: x.provs.nomeAppProv, 
                id: 'ui', arqs: x.provs.testeUiNomeProv.map { "${it}Files" } 
            ]
        ]
        List<Map<String, Object>> alvos = [ appAlvosMap ] + testAlvos 
        Map<String, Object> uuidsMap = [:] // mapa aninhado para guardar UUIDs por caminho lógico
        Map<String, List<String>> ePBXMap = [:] // mapa para agrupar elementos PBX por tipo
        Map<String, String> arqsTesteMap = testAlvos.collectEntries { Map alvoTesteMap ->
            [(alvoTesteMap.nome.get()): alvoTesteMap.arqs.get()] // mapeia AppUiTests
        } 
        Map provs = alvos.collectEntries { Map alvoMap -> // PréCalc provs  nomes-alvos em cada plat
            Provider<String> nomeProdProv = alvoMap.nome
            String nomeBase = nomeProdProv.get() 
            Map entradasPlataformaMap = plataformas.collectEntries { String plataforma ->
                Map<String, Provider<String>> plataformaMap = [
                    nomeAlvoProv: nomeProdProv.map { "${it}-${plataforma}" }
                ]
                if (alvoMap.sede) { // Adiciona chaves extras se for um target de teste
                    plataformaMap.nomeProdProv = nomeProdProv
                    plataformaMap.alvoNomeSedeProv = alvoMap.sede.map { "${it}-${plataforma}" }
                }
                [(plataforma): plataformaMap]
            }
            [(nomeBase): entradasPlataformaMap]
        }
        descobreArqs(
            ePBXMap, srcTestSwiftDirProv.get().getAsFile(), x.provs.srcDirProv.get().getAsFile(), 
            resourcesDirProv.get().getAsFile(), espolioDirProv.get().getAsFile(), arqsTesteMap)
        Map refsMap = processaReferencias(uuidsMap, ePBXMap, testAlvos, arqsTesteMap)
        Map<String, String> atrbAlvosMap = criaAlvo(uuidsMap, ePBXMap, alvos, plataformas, 
            refsMap.recs, refsMap.testes, refsMap.fontes, provs, nomeApp, idPacote, verSwift)
        criaProjetoBasePBX(uuidsMap, ePBXMap, atrbAlvosMap, refsMap.groupFontes, nomeApp, idPacote, 
            verSwift, xcodeProjDir)
        escreveArquivosFinais(uuidsMap, ePBXMap, provs, xcPBXProjArqProv.get().getAsFile(), 
            xcSchemesDirProv.get().getAsFile(), plataformas, appAlvosMap, testAlvos, xcodeProjDir)
    }
}
// Cria o ícone do aplicativo
tasks.register('xIcone') {
    group = 'Xcode Actions'
    description = 'Gera o Assets.xcassets para o Xcode'

    Provider<RegularFile> fundoSvgProv = espolioDirProv.map { it.file('icones/appBackground.svg') }
    Provider<RegularFile> frenteSvgProv = espolioDirProv.map { it.file('icones/appForeground.svg') }
    
    inputs.files(fundoSvgProv, frenteSvgProv)
    outputs.dir xcassetsDirProv
    
    doLast { 
        File fundoSVG = fundoSvgProv.get().getAsFile()
        File frenteSVG = frenteSvgProv.get().getAsFile()
        File xcassetsDir = xcassetsDirProv.get().getAsFile()

        if (!fundoSVG.exists()) throw new GradleException('Faltou o SVG de Fundo!')
        if (!frenteSVG.exists()) throw new GradleException('Faltou o SVG de Frente!')
        // Cria a estrutura exata do Xcode: Assets.xcassets/AppIcon.xcassetsDir
        File iconeDir = new File(xcassetsDir, 'AppIcon.appiconset')
        if (!iconeDir.exists()) iconeDir.mkdirs()

        List<String> mesclaSVG = [
            x.provs.eMacProv.get() ? 'magick' : 
            "${x.provs.winDiscProv.get()}:/msys64/ucrt64/bin/magick.exe", 
            '-background', 'none', 
            fundoSVG.absolutePath, 
            frenteSVG.absolutePath, 
            '-gravity', 'center', '-composite', 
            '-resize', '1024x1024!', 
            '-alpha', 'remove',
            new File(iconeDir, 'app_apple_1024.png').absolutePath 
        ]
        
        Process processo = mesclaSVG.execute()
        processo.waitForProcessOutput(System.out, System.err)
        if (processo.exitValue() != 0) throw new GradleException('Falha no ImageMagick (Apple)')
        // Escreve o manifesto JSON que diz ao compilador do Xcode o que é essa imagem
        new File(iconeDir, 'Contents.json').text = """
        {
            \"images\" : [
                {
                    \"filename\" : \"app_apple_1024.png\",
                    \"idiom\" : \"universal\",
                    \"platform\" : \"ios\",
                    \"size\" : \"1024x1024\"
                },
                {
                    \"filename\" : \"app_apple_1024.png\",
                    \"idiom\" : \"mac\",
                    \"scale\" : \"1x\",
                    \"size\" : \"512x512\"
                },
                {
                    \"filename\" : \"app_apple_1024.png\",
                    \"idiom\" : \"mac\",
                    \"size\" : \"512x512\",
                    \"scale\" : \"2x\"
                }
            ],
            \"info\" : {
                \"author\" : \"xcode\",
                \"version\" : 1
            }
        }""".stripIndent().trim()
    }
}
// Biblioteras para serem usadas no código
// dependencies {}