// Declaração dos plugins
// plugins {}
plugins.apply(libs.plugins.buildLogicXcodeGeral.get().getPluginId())
// application {} // Define configurações do swift-application (incompativel com gradle 9 [11/2025])
// Atalhos para facilitar a leitura
Object x = project.ext.get('xcodeVars')
// Definição de provedores para acesso à valores de configuração e diretórios
Provider<String> vmXcodeDirProv = x.vmDirProv.zip(x.buildXDirProv) { String dir, String bDir -> 
    new File(dir.toString(), bDir).path.replace(File.separator, '/')
}
Provider<Directory> xcDirProv = project.providers.provider { 
    project.rootProject.layout.projectDirectory.dir(x.buildXDirProv.get()) 
}
// Busca um simulador de iOS disponível para testes e armazena em cache
String cacheSimulador // cache manual para pegaSimulador
Closure<String> pegaSimulador = { ->
    if (cacheSimulador) { return cacheSimulador } // Retorna o valor em cache se exisitr
    String simuladorUsual = x.simuladorUsualProv.get()
    String saida = ''
    // Executa o comando para listar os dispositivos simulados em JSON
    try { // O try/catch age como ignoreExitValue, se o comando falhar a saida continua vazia
        ByteArrayOutputStream saidaStd = new ByteArrayOutputStream()
        ByteArrayOutputStream erroStd = new ByteArrayOutputStream() // captura o erro
        Process processo = x.comandoRemoto(['xcrun', 'simctl list -j devices']).execute()
        processo.waitForProcessOutput(saidaStd, erroStd) // pega a saída e espera o comando terminar
        String erro = erroStd.toString().trim()
        saida = saidaStd.toString().trim()

        if (!erro.isEmpty()) { println ">> ERRO: falha ao listar simuladores. ${erro}" }
    } catch (Exception e) { 
        println ">> AVISO: falha ao executar. Usando '${simuladorUsual}'. ${e.message}" 
    }
    // Verifica se o comando produziu alguma saída
    if (saida.isBlank()) {
        println ">> AVISO: falha ao pegar simulador instalado. Usando '${simuladorUsual}'."
        return (cacheSimulador = simuladorUsual)
    }
    // Pega todos os dispositivos de todos os runtimes em uma única lista
    try {
        Map<String, Object> jsonSaidaMap = new groovy.json.JsonSlurper().parseText(saida)
        List<Map<String, Object>> aparelhos = jsonSaidaMap.devices.values().flatten()
        // PRIORIDADE 1: Encontrar qualquer simulador que já esteja ativo ('Booted')
        Map<String, Object> aparelhoAtivoMap = aparelhos.find { it.state == 'Booted' }
        if (aparelhoAtivoMap) { return (cacheSimulador = aparelhoAtivoMap.name) }
        // PRIORIDADE 2: Se nenhum estiver ativo, encontrar o primeiro iPhone ou iPad disponível
        Map<String, Object> aparelhoPreparadoMap = aparelhos.find {
            it.isAvailable && (it.name.startsWith('iPhone') || it.name.startsWith('iPad'))
        }
        if (aparelhoPreparadoMap) { return (cacheSimulador = aparelhoPreparadoMap.name) }
    } catch (Exception e) { 
        println ">> AVISO: falha de leitura. Usando '${simuladorUsual}'. ${e.message}" 
    }
    return (cacheSimulador = simuladorUsual)
}
// Retorna um caminho de diretório (String) absoluto, seja local ou remoto (na VM)
Closure<String> pegaDir = { String sobDir, String subDir ->
    if (x.eMacProv.get()) { return xcDirProv.get().dir(sobDir).dir(subDir).asFile.absolutePath } 
    else { return "${vmXcodeDirProv.get()}/${sobDir}/${subDir}" }
}
// Retorna arquivos para os artefatos de build. Retorna vazio se estiver em modo remoto
Closure<Provider<FileCollection>> pegaArquivos = {String subDir ->
    if (x.eMacProv.get()) {return project.layout.files(xcDirProv.get().dir('products').dir(subDir))} 
    else { return project.layout.files(new File("${vmXcodeDirProv.get()}/products/${subDir}")) }
}
Closure<String> pegaArchiveDir = { String platforma ->
    "${pegaDir('derived-data', platforma)}/${x.nomeAppProv.get()}-${platforma}.xcarchive"
}
// Tarefa para sincronizar os arquivos do diretório app para a VM MacOS
tasks.register('syncToMac') { // caso necessário use "--rerun" para forçar a reexecução
    description = 'Garante que o diretório existe, sincroniza os arquivos e ajusta as permissões.'
    group = 'MacOs Controller'
    onlyIf { !x.eMacProv.get() } // executa apenas se não for MacOS local
    inputs.files(x.projDirProv.map { Directory dir -> dir.asFileTree.matching {
        exclude 'build/**'
        exclude '.gradle/**'
        exclude 'build.gradle' // exclui o build.gradle dentro de x.projDirProv, se existir
    }})
    outputs.upToDateWhen { true } // só sincroniza 1 vez, neessário para não apagar as builds

    Provider<Directory> espolioDirProv = project.rootProject.layout.projectDirectory.dir(
        providers.gradleProperty('espolioDir').orElse('espolio')
    )
    // Executa o comando de limpeza e criação diretamente via SSH
    doFirst {
        List<String> preparoComandos = [
            'rm', '-rf', "\'${x.vmDirProv.get()}\'", '|| true &&', 
            'mkdir', '-p', "\'${x.vmAppDirProv.get()}\'"
        ]
        Process processoPreparo = x.comandoRemoto(preparoComandos).execute()
        processoPreparo.waitForProcessOutput(System.out, System.err)
        if (processoPreparo.exitValue() != 0) {
            throw new GradleException('Falha ao preparar os diretórios na VM.')
        }
    }
    
    doLast {
        String vmEntrada = x.comandoRemoto(['']).find { it.contains('@') }
        String vmProjDir = x.vmDirProv.get()
        String vmAppDir = x.vmAppDirProv.get()
        String vmResDir = "${vmAppDir}/src/main/resources"
        
        x.projDirProv.get().asFile.eachFile { File arq ->
            if (arq.name in ['.gradle', 'build', 'build.gradle']) { return }
            
            List<String> copiaCmds = [
                'scp', '-r', '-p', arq.absolutePath, "${vmEntrada}:${vmAppDir}"
            ]
            Process processoCopia = copiaCmds.execute()
            processoCopia.waitForProcessOutput(System.out, System.err)
            if (processoCopia.exitValue() != 0) {
                throw new GradleException("Falha ao sincronizar o arq '${arq.name}' para a VM.")
            }
        }

        espolioDirProv.get().asFile.eachFile { File arq ->
            List<String> copiaCmds = [
                'scp', '-r', '-p', arq.absolutePath, "${vmEntrada}:${vmResDir}"
            ]
            Process processoRecursos = copiaCmds.execute()
            processoRecursos.waitForProcessOutput(System.out, System.err)
            if (processoRecursos.exitValue() != 0) {
                throw new GradleException("Falha ao sincronizar o arq \'${arq.name}\' para a VM.")
            }
        }

        File geradoDir = xcDirProv.get().dir('generated').asFile
        if (geradoDir.exists()) {
            String vmBuildXCodeDir = "${vmAppDir}/${x.buildXDirProv.get()}"
            // Garante que a pasta build/xcode exista na VM antes de copiar
            x.comandoRemoto(
                ['mkdir', '-p', "\'${vmBuildXCodeDir}\'"]
            ).execute().waitForProcessOutput(System.out, System.err)
            
            List<String> copiaGeradaCmds = [
                'scp', '-r', '-p', geradoDir.absolutePath, "${vmEntrada}:${vmBuildXCodeDir}/"
            ]
            Process processoGereda = copiaGeradaCmds.execute()
            processoGereda.waitForProcessOutput(System.out, System.err)
            if (processoGereda.exitValue() != 0) {
                throw new GradleException('Falha ao sincronizar a pasta generated para a VM.')
            }
        }

        List<String> permissoesCmds = [
            'sudo', 'chown', '-R', "${vmEntrada.split('@')[0]} \'${vmProjDir}\'", '&&', 
            'sudo', 'chmod', '-R u+rwX', "\'${vmProjDir}\'"
        ]
        Process processoPermissoes = x.comandoRemoto(permissoesCmds).execute()
        processoPermissoes.waitForProcessOutput(System.out, System.err)
        if (processoPermissoes.exitValue() != 0) { 
            throw new GradleException('Falha ao ajustar permissões') 
        }
    }
}
// Tarefa para limpar os arquivos de build do Xcode
tasks.register('cleanMac', Exec) {
    description = 'Limpa os arquivos de build do Xcode para iOS.'
    group = 'MacOs Controller'
    workingDir(x.projDirProv)
    outputs.upToDateWhen { false } // sempre executa 

    doFirst {
        String simulador = pegaSimulador()
        String dirXc = x.eMacProv.get() ? xcDirProv.get().asFile.absolutePath : vmXcodeDirProv.get()
        String donoMac = '\$(getconf DARWIN_USER_CACHE_DIR)' // pra reduzir o tamanho da linha

        commandLine x.comandoRemoto([
            // Finaliza Processos e Executa o Clean Oficial
            'killall', 'Xcode', '|| true &&',
            'xcrun', '-k', '|| true &&',
            // Limpa Caches do Compilador e do Sistema
            'rm', '-rf', "\'${donoMac}/org.llvm.clang/ModuleCache\'", '|| true &&',
            'rm', '-rf', "\'${donoMac}/org.llvm.clang.\$(whoami)/ModuleCache\'", '|| true &&',
            'rm', '-rf', "\'${donoMac}/com.apple.dt.Xcode/*\'", '|| true &&',
            // Limpa Caches do Usuário e do Xcode
            'rm', '-rf', '\'~/Library/Developer/Xcode/DerivedData/*\'', '|| true &&',
            'rm', '-rf', '\'~/Library/Developer/Xcode/UserData/Previews/*\'', '|| true &&',
            'rm', '-rf', '\'~/Library/Caches/com.apple.dt.Xcode/*\'', '|| true &&',
            // Limpa Caches de Suporte a Dispositivos Físicos
            'rm', '-rf', '\'~/Library/Developer/Xcode/iOS DeviceSupport/*\'', '|| true &&',
            'rm', '-rf', '\'~/Library/Developer/Xcode/watchOS DeviceSupport/*\'', '|| true &&',
            'rm', '-rf', '\'~/Library/Developer/Xcode/tvOS DeviceSupport/*\'', '|| true &&',
            'rm', '-rf', '\'~/Library/Developer/Xcode/visionOS DeviceSupport/*\'', '|| true &&',
            // Limpa Caches do Simulador
            'xcrun', 'simctl shutdown', "\'${simulador}\'", '|| true &&',
            'xcrun', 'simctl erase', "\'${simulador}\'", '|| true &&',
            // Apaga o Diretório do Projeto
            'rm', '-rf', "\'${dirXc}\'", '|| true'
        ])
    }
}
// Cria tarefas de build para cada plataforma e configuração
Closure<Void> xbuild = { Task tarefa, String platforma, String sdk, String config ->
    tarefa.description = "Compila o projeto Xcode para ${platforma.toUpperCase()} (${config})"
    tarefa.group = 'Xcode Actions'
    tarefa.inputs.dir x.srcDirProv
    tarefa.inputs.dir x.xcodeProjProv
    tarefa.inputs.files(tasks.named('syncToMac')) // garante sync antes do build, se remoto
    tarefa.outputs.dir({ -> x.eMacProv.get() ? pegaArquivos("${config}-${sdk}") : null}).optional()

    tarefa.doFirst { // Configura o comando de build do Xcode
        List<String> comandos = [
            'xcrun', 'xcodebuild', 'build', 'CODE_SIGN_IDENTITY=-', 'CODE_SIGNING_REQUIRED=NO',
            '-project', x.xcodeProjProv.get(),
            '-configuration', config,
            '-sdk', sdk,
            '-scheme', "${x.nomeAppProv.get()}-${platforma == 'ios' ? 'iOS' : 'macOS'}",
            '-derivedDataPath', pegaDir('derived-data', platforma)
        ]
        // Caso iOS, adiciona o destino do simulador
        if (platforma == 'ios') { comandos.addAll([ 
            '-destination', "platform=\'iOS Simulator\',name=\'${pegaSimulador()}\'" 
        ])} else { comandos.addAll([ '-destination', "platform=macOS,name=\'My Mac\'" ]) }

        tarefa.commandLine = x.comandoRemoto(comandos)
    }
}
// Registra as tarefas de build para cada plataforma e configuração
tasks.register('buildMacos', Exec) { xbuild(it, 'macos', 'macosx', 'Debug') }
tasks.register('buildIos', Exec) { xbuild(it, 'ios', 'iphonesimulator', 'Debug') }
// Cria tarefas para executar o app compilado
Closure<Void> xrun = { Task tarefa, String platforma, String sdk, String config ->
    tarefa.description = "Executa o app compilado para ${platforma.toUpperCase()} (${config})"
    tarefa.group = 'Xcode Actions'
    tarefa.inputs.files(tasks.named("build${platforma.capitalize()}")) // depende do build
    tarefa.inputs.files(pegaArquivos("${config}-${sdk}"))
    tarefa.outputs.upToDateWhen { false } // sempre executa

    tarefa.doFirst {
        List<String> comandos = []
        String app = "${pegaDir('products', "${config}-${sdk}")}/${x.nomeAppProv.get()}.app"
        // Caso iOS, usa simctl para instalar e lançar no simulador
        if (platforma == 'ios') { 
            String sim = pegaSimulador()
            comandos.addAll([
            'xcrun', 'simctl boot', "\'${sim}\'", '|| true &&',
            'open', '-a Simulator', '|| true &&',
            'xcrun', 'simctl bootstatus', "\'${sim}\'", '&&',
            'xcrun', 'simctl install', "\'${sim}\'", "\'${app}\'", '&&',
            'xcrun', 'simctl launch', "\'${sim}\'", "\'${x.xcIdPacoteAppProv.get()}.ios\'"
        ])} else { comandos.addAll(['open', app]) } // caso macOS, usa open diretamente
        
        tarefa.commandLine = x.comandoRemoto(comandos)
    }
}
// Registra as tarefas de execução para cada plataforma e configuração
tasks.register('runMacos', Exec) { xrun(it, 'macos', 'macosx', 'Debug') }
tasks.register('runIos', Exec) { xrun(it, 'ios', 'iphonesimulator', 'Debug') }
// Cria tarefas para executar os testes
Closure<Void> xtest = { Task tarefa, String platforma, String sdk, Provider<String> nomeTestProv ->
    tarefa.description = "Executa os testes para ${platforma.toUpperCase()}"
    tarefa.group = 'Xcode Actions'
    // Dependência implícita do build
    tarefa.inputs.files({ -> x.eMacProv.get() ? pegaArquivos("Debug-${sdk}") : null }).optional()
    tarefa.inputs.files(tasks.named('syncToMac')) // garante sync antes do teste, se remoto

    tarefa.doFirst {
        String nomeTeste = nomeTestProv.get()
        String derivedDataDir = pegaDir('derived-data', platforma)
        String resultadoPacoteArq = "${derivedDataDir}/TestResults-${nomeTeste}.xcresult"
        // Garante que o diretório de resultados anterior seja limpo
        if (x.eMacProv.get()) { // Caso MacOS: Usa rm -rf
            File resultadoPacoteDir = new File(resultadoPacoteArq)
            // Caso Local deleta o diretório .xcresult diretamente
            if (resultadoPacoteDir.exists()) { resultadoPacoteDir.deleteDir() }
        } else { // Caso Remoto executa rm -rf via SSH
            List<String> removerCmds = ['rm', '-rf', "\'${resultadoPacoteArq}\'"]
            Process processoRemover = x.comandoRemoto(removerCmds).execute()
            processoRemover.waitForProcessOutput(System.out, System.err) // para ver os logs
            if (processoRemover.exitValue() != 0) {
                throw new GradleException('Falha ao limpar resultados de teste antigos na VM.')
            }
        }
        // Configura o comando de teste do Xcode
        List<String> comandos = [
            'xcrun', 'xcodebuild', 'test',
            '-project', x.xcodeProjProv.get(),
            '-scheme', "${nomeTeste}-${platforma == 'ios' ? 'iOS' : 'macOS'}",
            '-configuration', 'Debug',
            '-derivedDataPath', derivedDataDir,
            '-resultBundlePath', resultadoPacoteArq,
            '-sdk', sdk,
        ]
        // Caso iOS, adiciona o destino do simulador
        if (platforma == 'ios') { 
            comandos.addAll(['-destination', "\'platform=iOS Simulator,name=${pegaSimulador()}\'"])
        } else { comandos.addAll(['-destination', "\'platform=macOS,name=My Mac\'"]) }

        tarefa.commandLine = x.comandoRemoto(comandos)
    }
}
// Registra as tarefas de teste para cada plataforma e configuração
tasks.register('testMacosUnit', Exec) { xtest(it, 'macos', 'macosx', x.xcUnitTesteNomeProv) }
tasks.register('testMacosUi', Exec) { xtest(it, 'macos', 'macosx', x.xcUITesteNomeProv) }
tasks.register('testIosUnit', Exec) { xtest(it, 'ios', 'iphonesimulator', x.xcUnitTesteNomeProv) }
tasks.register('testIosUi', Exec) { xtest(it, 'ios', 'iphonesimulator', x.xcUITesteNomeProv) }
// Cria um arquivo .xcarchive para distribuição
Closure<Void> xarchive = { Task tarefa, String platforma, String sdk ->
    tarefa.description = "Cria um arquivo .xcarchive para ${platforma.toUpperCase()} (Release)"
    tarefa.group = 'Xcode Actions'
    tarefa.inputs.dir x.srcDirProv
    tarefa.inputs.dir x.xcodeProjProv
    tarefa.inputs.files(tasks.named('syncToMac'))
    tarefa.outputs.file(x.eMacProv.flatMap { Boolean eMac ->
        if (eMac) { return providers.provider {
            project.rootProject.layout.projectDirectory.file(pegaArchiveDir(platforma)) }
        } else { return providers.provider { null } }
    }).optional()
    // O Archive usa uma configuração específica de Release
    tarefa.doFirst {
        String idTimeProv = x.idTimeProv.get()
        List<String> comandos = [
            'xcrun', 'xcodebuild', 'archive',
            '-project', x.xcodeProjProv.get(),
            '-scheme', "${x.nomeAppProv.get()}-${platforma == 'ios' ? 'iOS' : 'macOS'}",
            '-sdk', sdk,
            '-archivePath', pegaArchiveDir(platforma),
            'BUILD_LIBRARY_FOR_DISTRIBUTION=YES',
            "INFOPLIST_KEY_LSApplicationCategoryType=public.app-category.${x.categoriaProv.get()}"
        ]
        // Configuração de destino, iOS precisa de destino explícito
        if (platforma == 'ios') { comandos.addAll([ '-destination', 'generic/platform=iOS' ]) }
        else { comandos.addAll([ '-destination', 'platform=macOS' ]) }
        // Configuração de credenciais
        if (idTimeProv != 'TAPABURACO') { comandos.addAll([ 
            'CODE_SIGNING_REQUIRED=YES', "DEVELOPMENT_TEAM=${idTimeProv}",
            "CODE_SIGN_IDENTITY=\'Apple Distribution: ${x.nomePerfilProv.get()} (${idTimeProv})\'", 
            "PROVISIONING_PROFILE_SPECIFIER=\'${x.nomePerfilProv.get()}\'"
        ])} else { comandos.addAll([ 
            'CODE_SIGN_IDENTITY=-', 'CODE_SIGNING_ALLOWED=NO', 'CODE_SIGNING_REQUIRED=NO', 
            'PROVISIONING_PROFILE=', 'PROVISIONING_PROFILE_SPECIFIER=' 
        ])}

        tarefa.commandLine = x.comandoRemoto(comandos)
    }
}
// Registro das tarefas de arquivamento para cada plataforma
tasks.register('archiveMacos', Exec) { xarchive(it, 'macos', 'macosx') }
tasks.register('archiveIos', Exec) { xarchive(it, 'ios', 'iphoneos') }
// Valida e assina o aplicativo, (não funciona, não tenho nenhuma chave de desenvolvedor válida)
Closure<Void> xexport = { Task tarefa, String platforma ->
    tarefa.description = 'Exporta o apliativo.xcarchive para AppStore'
    tarefa.group = 'Xcode Actions'
    tarefa.inputs.files(tasks.named("archive${platforma.capitalize()}")) // dependência implicita
    tarefa.outputs.file(x.eMacProv.map { Boolean eMac ->
        if (eMac) {
            String exportExt = (platforma == 'ios' ? 'ipa' : 'pkg')
            return "${pegaDir('derived-data', platforma)}/Exported-Products/Logger.${exportExt}"
        } else { return null }
    }).optional()

    tarefa.doFirst {
        String exportDir = "${pegaDir('derived-data', platforma)}/Exported-Poducts"
        String plistDir = "${x.xcodeProjProv.get()}/exportOptions.plist"
        String localPlistDir = new File(x.projDirProv.get().asFile, plistDir).absolutePath
        // Comando de Exportação requer um .plist, criado em xcode-project
        tarefa.commandLine = x.comandoRemoto([
            'xcrun', 'xcodebuild', '-exportArchive',
            '-archivePath', pegaArchiveDir(platforma),
            '-exportPath', exportDir,
            '-exportOptionsPlist', x.eMacProv.get() ? localPlistDir : plistDir
        ])
    }
}
// Registra as tarefas de exportação para cada plataforma
tasks.register('exportMacos', Exec) { xexport(it, 'macos') }
tasks.register('exportIos', Exec) { xexport(it, 'ios') }
// Envia o app exportado para o App Store Connect
Closure<Void> xsubmit = { Task tarefa, String platforma ->
    tarefa.description = "Envia o pacote (${platforma}) exportado para o App Store Connect"
    tarefa.group = 'Xcode Actions'
    tarefa.inputs.files(tasks.named("export${platforma.capitalize()}"))

    tarefa.doFirst {
        String exportDir = "${pegaDir('derived-data', platforma)}/Exported-Poducts"
        
        tarefa.commandLine = x.comandoRemoto([
            'xcrun', 'altool', '--upload-app',
            '--username', x.appleIdProv.get(), 
            '--password', x.appleSenhaProv.get(),
            '--file', "${exportDir}/${x.nomeAppProv.get()}.${(platforma == 'ios' ? 'ipa' : 'pkg')}" 
        ])
    }
}
// Registra as tarefas de submissão para cada plataforma
tasks.register('submitIos', Exec) { xsubmit(it, 'ios') }
tasks.register('submitMacos', Exec) { xsubmit(it, 'macos') }
// Biblioteras para serem usadas no código
// dependencies {}