// Declaração dos plugins
// plugins {}
plugins.apply(libs.plugins.buildLogicXcodeGeral.get().getPluginId())
// application {} // Define configurações do swift-application (incompativel com gradle 9 [11/2025])
// Atalhos para facilitar a leitura
Object xcConfig = project.extensions.getByType(XcConfig)
Provider<Map<String, String>> localPropsProv = providers.of(LeitorProps) { 
    String nomeArq = providers.gradleProperty('localPropertiesNome').getOrElse('local.properties')
    parameters.propertiesFile.set(new File(project.rootDir, nomeArq))
}
Provider<Map<String, String>> progPropsProv = providers.of(LeitorProps) { 
    String nomeArq = providers.gradleProperty('progPropertiesNome').getOrElse('programa.properties')
    parameters.propertiesFile.set(new File(project.rootDir, nomeArq))
}
Provider<Map<String, String>> secretoPropsProv = providers.of(LeitorProps) { 
    String nomeArq = providers.gradleProperty('scrtPropertiesNome').getOrElse('programa.properties')
    parameters.propertiesFile.set(new File(project.rootDir, nomeArq))
}
// Definição de provedores para acesso à valores de configuração e diretórios
Provider<String> vmXcodeDirProv = xcConfig.vmDir.zip(xcConfig.buildXDir) { 
    String dir, String bDir -> new File(dir.toString(), bDir).path.replace(File.separator, '/')
}
Provider<Directory> xcDirProv = xcConfig.rootDir.zip(xcConfig.buildXDir) { 
    Directory raiz, String buildX -> raiz.dir(buildX) 
}
Provider<String> appleIdProv = secretoPropsProv.map { it.get('apple.appleId') }
Provider<String> appleSenhaProv = secretoPropsProv.map { it.get('apple.senha') }
Provider<String> certificadoProv = secretoPropsProv.map { it.get('apple.certificado') }
Provider<String> nomePerfilProv = secretoPropsProv.map { it.get('apple.nomePerfil') }
Provider<String> simuladorUsualProv = localPropsProv.map { it.get('simulador.ios') }
// Busca um simulador de iOS disponível e armazena em cache
Closure<String> pegaSimulador = {
    String simuladorUsual = simuladorUsualProv.get()
    String saida = ''
    // Executa o comando para listar os dispositivos simulados em JSON
    try { // O try/catch age como ignoreExitValue, se o comando falhar a saida continua vazia
        ByteArrayOutputStream saidaStd = new ByteArrayOutputStream()
        ByteArrayOutputStream erroStd = new ByteArrayOutputStream() // captura o erro
        Process processo = xcConfig.comandoRemoto(['xcrun', 'simctl list -j devices']).execute()
        processo.waitForProcessOutput(saidaStd, erroStd) // pega a saída e espera o comando terminar
        String erro = erroStd.toString().trim()
        saida = saidaStd.toString().trim()

        if (!erro.isEmpty()) { println ">> ERRO: falha ao listar simuladores. ${erro}" }
    } catch (Exception e) { 
        println ">> AVISO: falha ao executar. Usando '${simuladorUsual}'. ${e.message}" 
    }
    // Verifica se o comando produziu alguma saída
    if (saida.isBlank()) {
        println ">> AVISO: falha ao pegar simulador instalado. Usando '${simuladorUsual}'."
        return simuladorUsual
    }
    // Pega todos os dispositivos de todos os runtimes em uma única lista
    try {
        Map<String, Object> jsonSaidaMap = new groovy.json.JsonSlurper().parseText(saida)
        List<Map<String, Object>> aparelhos = jsonSaidaMap.devices.values().flatten()
        // PRIORIDADE 1: Encontrar qualquer simulador que já esteja ativo ('Booted')
        Map<String, Object> aparelhoAtivoMap = aparelhos.find { it.state == 'Booted' }
        if (aparelhoAtivoMap) { return aparelhoAtivoMap.name }
        // PRIORIDADE 2: Se nenhum estiver ativo, encontrar o primeiro iPhone ou iPad disponível
        Map<String, Object> aparelhoPreparadoMap = aparelhos.find {
            it.isAvailable && (it.name.startsWith('iPhone') || it.name.startsWith('iPad'))
        }
        if (aparelhoPreparadoMap) { return aparelhoPreparadoMap.name }
    } catch (Exception e) { 
        println ">> AVISO: falha de leitura. Usando '${simuladorUsual}'. ${e.message}" 
    }
    return simuladorUsual
}
// Retorna o executable com base no SO
Closure<String> pegaExecutavelBase = { xcConfig.eMac.get() ? 'bash' : 'ssh' }
// Retorna um caminho absoluto de diretório, seja local ou remoto
Closure<String> pegaDir = { String sobDir, String subDir ->
    if (xcConfig.eMac.get()) { return xcDirProv.get().dir(sobDir).dir(subDir).asFile.absolutePath } 
    else { return "${vmXcodeDirProv.get()}/${sobDir}/${subDir}" }
}
// Retorna arquivos para os artefatos de build. Retorna vazio se estiver em modo remoto
Closure<Provider<FileCollection>> pegaArquivos = { String subDir ->
    if (xcConfig.eMac.get()) {
        return project.layout.files(xcDirProv.get().dir('products').dir(subDir)) 
    } 
    else { return project.layout.files(new File("${vmXcodeDirProv.get()}/products/${subDir}")) }
}
// Retorna um caminho de derived-data para cada plataforma
Closure<String> pegaArchiveDir = { String platforma ->
    "${pegaDir('derived-data', platforma)}/${xcConfig.nomeApp.get()}-${platforma}.xcarchive"
}
// Tarefa para sincronizar os arquivos do diretório app para a VM MacOS
tasks.register('syncToMac') { // caso necessário use "--rerun" para forçar a reexecução
    description = 'Garante que o diretório existe, sincroniza os arquivos e ajusta as permissões.'
    group = 'MacOs Controller'
    onlyIf { !xcConfig.eMac.get() } // executa apenas se não for MacOS local
    inputs.files(tasks.named('xproj'))
    inputs.files(tasks.named('xIcone'))
    inputs.files(xcConfig.projDir.map { it.asFileTree.matching {
        exclude 'build/**'
        exclude '.gradle/**'
        exclude 'build.gradle' // exclúi o build.gradle dentro de xcConfig.projDir, se existir
    }})
    outputs.upToDateWhen { true } // só sincroniza 1 vez, neessário para não apagar as builds

    Provider<Directory> espolioDirProv = xcConfig.rootDir.zip(progPropsProv) { 
        Directory raiz, String esp -> raiz.dir(esp.getOrDefault('espolioDir', 'espolio')) 
    }
    Provider<Directory> geradoDirProv = xcConfig.rootDir.zip(xcConfig.buildXDir) { 
        Directory raiz, String buildX -> raiz.dir("${buildX}/generated") 
    }
    // Executa o comando de limpeza e criação diretamente via SSH
    doFirst {
        List<String> preparoComandos = [
            'rm', '-rf', "\'${xcConfig.vmDir.get()}\'", '|| true &&', 
            'mkdir', '-p', "\'${xcConfig.vmAppDir.get()}\'"
        ]
        Process processoPreparo = xcConfig.comandoRemoto(preparoComandos).execute()
        processoPreparo.waitForProcessOutput(System.out, System.err)
        if (processoPreparo.exitValue() != 0) {
            throw new GradleException('Falha ao preparar os diretórios na VM.')
        }
    }
    
    doLast {
        String vmEntrada = xcConfig.comandoRemoto(['']).find { it.contains('@') }
        String vmProjDir = xcConfig.vmDir.get()
        String vmAppDir = xcConfig.vmAppDir.get()
        String vmResDir = "${vmAppDir}/${XcConfig.RES_DIR}"
        
        xcConfig.projDir.get().asFile.eachFile { File arq ->
            if (arq.name in ['.gradle', 'build', 'build.gradle']) { return }
            
            List<String> copiaCmds = [
                'scp', '-r', '-p', arq.absolutePath, "${vmEntrada}:${vmAppDir}"
            ]
            Process processoCopia = copiaCmds.execute()
            processoCopia.waitForProcessOutput(System.out, System.err)
            if (processoCopia.exitValue() != 0) {
                throw new GradleException("Falha ao sincronizar o arq '${arq.name}' para a VM.")
            }
        }

        espolioDirProv.get().asFile.eachFile { File arq ->
            List<String> copiaCmds = [
                'scp', '-r', '-p', arq.absolutePath, "${vmEntrada}:${vmResDir}"
            ]
            Process processoRecursos = copiaCmds.execute()
            processoRecursos.waitForProcessOutput(System.out, System.err)
            if (processoRecursos.exitValue() != 0) {
                throw new GradleException("Falha ao sincronizar o arq \'${arq.name}\' para a VM.")
            }
        }
        
        File geradoDir = geradoDirProv.get().asFile
        if (geradoDir.exists()) {
            String vmBuildXCodeDir = "${vmProjDir}/${xcConfig.buildXDir.get()}"
            // Garante que a pasta build/xcode exista na VM antes de copiar
            xcConfig.comandoRemoto(
                ['mkdir', '-p', "\'${vmBuildXCodeDir}\'"]
            ).execute().waitForProcessOutput(System.out, System.err)
            
            List<String> copiaGeradaCmds = [
                'scp', '-r', '-p', geradoDir.absolutePath, "${vmEntrada}:${vmBuildXCodeDir}/"
            ]
            Process processoGereda = copiaGeradaCmds.execute()
            processoGereda.waitForProcessOutput(System.out, System.err)
            if (processoGereda.exitValue() != 0) {
                throw new GradleException('Falha ao sincronizar a pasta generated para a VM.')
            }
        }

        List<String> permissoesCmds = [
            'sudo', 'chown', '-R', "${vmEntrada.split('@')[0]} \'${vmProjDir}\'", '&&', 
            'sudo', 'chmod', '-R u+rwX', "\'${vmProjDir}\'"
        ]
        Process processoPermissoes = xcConfig.comandoRemoto(permissoesCmds).execute()
        processoPermissoes.waitForProcessOutput(System.out, System.err)
        if (processoPermissoes.exitValue() != 0) { 
            throw new GradleException('Falha ao ajustar permissões') 
        }
    }
}
// Tarefa para limpar os arquivos de build do Xcode
tasks.register('cleanMac', Exec) {
    description = 'Limpa os arquivos de build do Xcode para iOS.'
    group = 'MacOs Controller'
    workingDir(xcConfig.projDir)
    outputs.upToDateWhen { false } // sempre executa

    executable = pegaExecutavelBase()
    argumentProviders.add(new CommandLineArgumentProvider() {
        @Input Provider<Boolean> getEMacProv() { xcConfig.eMac }
        @Input Provider<String> getDirXcProv() { xcConfig.eMac.flatMap { Boolean ehMac ->
            ehMac ? xcDirProv.map { it.asFile.absolutePath } : vmXcodeDirProv 
        }}

        @Override Iterable<String> asArguments() {
            boolean eMac = getEMacProv().get()
            String simulador = pegaSimulador()
            String dirXc = getDirXcProv().get()
            String donoMac = '\$(getconf DARWIN_USER_CACHE_DIR)' // pra reduzir o tamanho da linha

            return xcConfig.comandoRemoto([
                // Finaliza Processos e Executa o Clean Oficial
                'killall', 'Xcode', '|| true &&',
                'xcrun', '-k', '|| true &&',
                // Limpa Caches do Compilador e do Sistema
                'rm', '-rf', "\'${donoMac}/org.llvm.clang/ModuleCache\'", '|| true &&',
                'rm', '-rf', "\'${donoMac}/org.llvm.clang.\$(whoami)/ModuleCache\'", '|| true &&',
                'rm', '-rf', "\'${donoMac}/com.apple.dt.Xcode/*\'", '|| true &&',
                // Limpa Caches do Usuário e do Xcode
                'rm', '-rf', '\'~/Library/Developer/Xcode/DerivedData/*\'', '|| true &&',
                'rm', '-rf', '\'~/Library/Developer/Xcode/UserData/Previews/*\'', '|| true &&',
                'rm', '-rf', '\'~/Library/Caches/com.apple.dt.Xcode/*\'', '|| true &&',
                // Limpa Caches de Suporte a Dispositivos Físicos
                'rm', '-rf', '\'~/Library/Developer/Xcode/iOS DeviceSupport/*\'', '|| true &&',
                'rm', '-rf', '\'~/Library/Developer/Xcode/watchOS DeviceSupport/*\'', '|| true &&',
                'rm', '-rf', '\'~/Library/Developer/Xcode/tvOS DeviceSupport/*\'', '|| true &&',
                'rm', '-rf', '\'~/Library/Developer/Xcode/visionOS DeviceSupport/*\'', '|| true &&',
                // Limpa Caches do Simulador
                'xcrun', 'simctl shutdown', "\'${simulador}\'", '|| true &&',
                'xcrun', 'simctl erase', "\'${simulador}\'", '|| true &&',
                // Apaga o Diretório do Projeto
                'rm', '-rf', "\'${dirXc}\'", '|| true'
            ]).drop(1)
        }
    })
}
// Cria tarefas de build para cada plataforma e configuração
Closure<Void> xbuild = { Task tarefa, String platforma, String sdk, String config ->
    tarefa.description = "Compila o projeto Xcode para ${platforma.toUpperCase()} (${config})"
    tarefa.group = 'Xcode Actions'
    tarefa.inputs.dir xcConfig.srcDir.get()
    tarefa.inputs.dir xcConfig.xcodeProj.get()
    tarefa.inputs.files(tasks.named('syncToMac')) // garante sync antes do build, se remoto
    tarefa.outputs.dir({xcConfig.eMac.get() ? pegaArquivos("${config}-${sdk}") : null}).optional()
    // Configura o comando de build do Xcode
    tarefa.executable = pegaExecutavelBase()
    tarefa.argumentProviders.add(new CommandLineArgumentProvider() {
        @Input Provider<String> getXcodeProjProv() { xcConfig.xcodeProj }
        @Input Provider<String> getNomeAppProv() { xcConfig.nomeApp }

        @Override Iterable<String> asArguments() {
            List<String> comandos = [
                'xcrun', 'xcodebuild', 'build', 'CODE_SIGN_IDENTITY=-', 'CODE_SIGNING_REQUIRED=NO',
                '-project', getXcodeProjProv().get(),
                '-configuration', config,
                '-sdk', sdk,
                '-scheme', "${getNomeAppProv().get()}-${platforma == 'ios' ? 'iOS' : 'macOS'}",
                '-derivedDataPath', pegaDir('derived-data', platforma)
            ]
            // Caso iOS, adiciona o destino do simulador
            if (platforma == 'ios') { comandos.addAll([
                '-destination', "platform=\'iOS Simulator\',name=\'${pegaSimulador()}\'"
            ])} else { comandos.addAll(['-destination', "platform=macOS,name=\'My Mac\'"]) }

            return xcConfig.comandoRemoto(comandos).drop(1)
        }
    })
}
// Registra as tarefas de build para cada plataforma e configuração
tasks.register('buildMacos', Exec) { xbuild(it, 'macos', 'macosx', 'Debug') }
tasks.register('buildMacosRelease', Exec) { xbuild(it, 'macos', 'macosx', 'Release') }
tasks.register('buildIos', Exec) { xbuild(it, 'ios', 'iphonesimulator', 'Debug') }
tasks.register('buildIosRelease', Exec) { xbuild(it, 'ios', 'iphonesimulator', 'Release') }
// Cria tarefas para executar o app compilado
Closure<Void> xrun = { Task tarefa, String platforma, String sdk, String config ->
    tarefa.description = "Executa o app compilado para ${platforma.toUpperCase()} (${config})"
    tarefa.group = 'Xcode Actions'
    tarefa.inputs.files(tasks.named("build${platforma.capitalize()}")) // depende do build
    tarefa.inputs.files(pegaArquivos("${config}-${sdk}"))
    tarefa.outputs.upToDateWhen { false } // sempre executa

    tarefa.executable = pegaExecutavelBase()
    tarefa.argumentProviders.add(new CommandLineArgumentProvider() {
        @Input Provider<String> getIdPacotAppProv() { xcConfig.xcIdPacoteApp }
        @Input Provider<String> getNomeAppProv() { xcConfig.nomeApp }

        @Override Iterable<String> asArguments() {
            String app = "${pegaDir('products', "${config}-${sdk}")}/${getNomeAppProv().get()}.app"
            List<String> comandos = []
            // Caso iOS, usa simctl para instalar e lançar no simulador
            if (platforma == 'ios') {
                String simulador = pegaSimulador()
                comandos.addAll([
                'xcrun', 'simctl boot', "\'${simulador}\'", '|| true &&',
                'open', '-a Simulator', '|| true &&',
                'xcrun', 'simctl bootstatus', "\'${simulador}\'", '&&',
                'xcrun', 'simctl install', "\'${simulador}\'", "\'${app}\'", '&&',
                'xcrun', 'simctl launch', "\'${simulador}\'", "\'${getIdPacotAppProv().get()}.ios\'"
            ])} else { comandos.addAll(['open', app]) }

            return xcConfig.comandoRemoto(comandos).drop(1)
        }
    })
}
// Registra as tarefas de execução para cada plataforma e configuração
tasks.register('runMacos', Exec) { xrun(it, 'macos', 'macosx', 'Debug') }
tasks.register('runIos', Exec) { xrun(it, 'ios', 'iphonesimulator', 'Debug') }
// Cria tarefas para executar os testes
Closure<Void> xtest = { Task tarefa, String platforma, String sdk, Provider<String> nomeTestProv ->
    tarefa.description = "Executa os testes para ${platforma.toUpperCase()}"
    tarefa.group = 'Xcode Actions'
    // Dependência implícita do build
    tarefa.inputs.files({ xcConfig.eMac.get() ? pegaArquivos("Debug-${sdk}") : null }).optional()
    tarefa.inputs.files(tasks.named('syncToMac')) // garante sync antes do teste, se remoto

    Provider<String> derivedDataDirProv = providers.provider { pegaDir('derived-data', platforma) }
    Provider<String> resultadoPacoteArqProv = derivedDataDirProv.zip(nomeTestProv) { 
        String dir, String nome -> "${dir}/TestResults-${nome}.xcresult"
    }

    tarefa.doFirst {
        String derivedDataDir = derivedDataDirProv.get()
        String resultadoPacoteArq = resultadoPacoteArqProv.get()
        // Garante que o diretório de resultados anterior seja limpo
        if (xcConfig.eMac.get()) { // Caso MacOS: Usa rm -rf
            File resultadoPacoteDir = new File(resultadoPacoteArq)
            // Caso Local deleta o diretório .xcresult diretamente
            if (resultadoPacoteDir.exists()) { resultadoPacoteDir.deleteDir() }
        } else { // Caso Remoto executa rm -rf via SSH
            Process processoRemover = xcConfig.comandoRemoto([
                'rm', '-rf', "\'${resultadoPacoteArq}\'"
            ]).execute()
            processoRemover.waitForProcessOutput(System.out, System.err) // para ver os logs
            if (processoRemover.exitValue() != 0) {
                throw new GradleException('Falha ao limpar resultados de teste antigos na VM.')
            }
        }
    }
    // Configura o comando de teste do Xcode
    tarefa.executable = pegaExecutavelBase()
    tarefa.argumentProviders.add(new CommandLineArgumentProvider() {
        @Input Provider<String> getNomeTestProv() { nomeTestProv }
        @Input Provider<String> getXcodeProjProv() { xcConfig.xcodeProj }
        @Input Provider<String> getDerivedDataDirProv() { derivedDataDirProv }
        @Input Provider<String> getResultadoPacoteArqProv() { resultadoPacoteArqProv }

        @Override Iterable<String> asArguments() {
            List<String> comandos = [
                'xcrun', 'xcodebuild', 'test',
                '-project', getXcodeProjProv().get(),
                '-scheme', "${getNomeTestProv().get()}-${platforma == 'ios' ? 'iOS' : 'macOS'}",
                '-configuration', 'Debug',
                '-derivedDataPath', getDerivedDataDirProv().get(),
                '-resultBundlePath', getResultadoPacoteArqProv().get(),
                '-sdk', sdk,
            ]
            // Caso iOS, adiciona o destino do simulador
            if (platforma == 'ios') { comandos.addAll([
                '-destination', "\'platform=iOS Simulator,name=${pegaSimulador()}\'"
            ])} else { comandos.addAll(['-destination', "\'platform=macOS,name=My Mac\'"]) }

            return xcConfig.comandoRemoto(comandos).drop(1)
        }
    })
}
// Registra as tarefas de teste para cada plataforma e configuração
tasks.register('testIosIntg', Exec) { xtest(it, 'ios', 'iphonesimulator', xcConfig.testeIntgNome) }
tasks.register('testIosUnit', Exec) { xtest(it, 'ios', 'iphonesimulator', xcConfig.testeUnitNome)}
tasks.register('testIosUi', Exec) { xtest(it, 'ios', 'iphonesimulator', xcConfig.testeUiNome) }
tasks.register('testMacosIntg', Exec) { xtest(it, 'macos', 'macosx', xcConfig.testeIntgNome) }
tasks.register('testMacosUnit', Exec) { xtest(it, 'macos', 'macosx', xcConfig.testeUnitNome) }
tasks.register('testMacosUi', Exec) { xtest(it, 'macos', 'macosx', xcConfig.testeUiNome) }
// Ordem das tarefas entre si
tasks.named('testMacosUi').configure { mustRunAfter 'testMacosUnit' }
tasks.named('testMacosIntg').configure { mustRunAfter 'testMacosUi' }
tasks.named('testIosUi').configure { mustRunAfter 'testIosUnit' }
tasks.named('testIosIntg').configure { mustRunAfter 'testIosUi' }
// configura o "--continue" apenas para as compilações de Testes
if (gradle.startParameter.taskNames.any { it.endsWith('testIos') || it.endsWith('testMacos') }) {
    gradle.startParameter.continueOnFailure = true
}
// Tarefas de test geral MacOS
tasks.register('testMacos') {
    description = 'Executa todos os testes do macOS em sequência.'
    group = 'Xcode Actions'
    dependsOn tasks.named('testMacosUnit'), tasks.named('testMacosUi'), tasks.named('testMacosIntg')
}
// Tarefas de test geral iOS
tasks.register('testIos') {
    description = 'Executa todos os testes do iOS em sequência.'
    group = 'Xcode Actions'
    dependsOn tasks.named('testIosUnit'), tasks.named('testIosUi'), tasks.named('testIosIntg')
}
// Cria um arquivo .xcarchive para distribuição
Closure<Void> xarchive = { Task tarefa, String platforma, String sdk ->
    tarefa.description = "Cria um arquivo .xcarchive para ${platforma.toUpperCase()} (Release)"
    tarefa.group = 'Xcode Actions'
    tarefa.inputs.dir xcConfig.srcDir.get()
    tarefa.inputs.dir xcConfig.xcodeProj.get()
    tarefa.inputs.files(tasks.named('syncToMac'))

    Provider<RegularFile> archiveArqProv = project.layout.file(project.provider { 
        new File(raizDir, pegaArchiveDir(platforma)) 
    })
    Provider<String> categoriaProv = progPropsProv.map { 
        it.getOrDefault('apple.category', 'app-store-connect') 
    }

    tarefa.outputs.file(xcConfig.eMac.flatMap { Boolean ehMac ->
        ehMac ? archiveArqProv : providers.provider { null }
    }).optional()
    // O Archive usa uma configuração específica de Release
    tarefa.executable = pegaExecutavelBase()
    tarefa.argumentProviders.add(new CommandLineArgumentProvider() {
        @Input Provider<String> getIdTimeProv() { xcConfig.idTime }
        @Input Provider<String> getCategoriaProv() { categoriaProv }
        @Input Provider<String> getNomePerfilProv() { nomePerfilProv }

        @Override Iterable<String> asArguments() {
            String idTime = getIdTimeProv().get()
            String categoria = getCategoriaProv().get()
            String perfil = getNomePerfilProv().get()
            
            List<String> comandos = [
                'xcrun', 'xcodebuild', 'archive',
                '-project', xcConfig.xcodeProj.get(),
                '-scheme', "${xcConfig.nomeApp.get()}-${platforma == 'ios' ? 'iOS' : 'macOS'}",
                '-sdk', sdk,
                '-archivePath', pegaArchiveDir(platforma),
                'BUILD_LIBRARY_FOR_DISTRIBUTION=YES',
                "INFOPLIST_KEY_LSApplicationCategoryType=public.app-category.${categoria}"
            ]
            // Configuração de destino, iOS precisa de destino explícito
            if (platforma == 'ios') { comandos.addAll([ '-destination', 'generic/platform=iOS' ]) }
            else { comandos.addAll([ '-destination', 'platform=macOS' ]) }
            // Configuração de credenciais
            if (idTime != 'TAPABURACO') { comandos.addAll([ 
                'CODE_SIGNING_REQUIRED=YES', "DEVELOPMENT_TEAM=${idTime}",
                "CODE_SIGN_IDENTITY=\'Apple Distribution: ${perfil} (${idTime})\'", 
                "PROVISIONING_PROFILE_SPECIFIER=\'${perfil}\'"
            ])} else { comandos.addAll([ 
                'CODE_SIGN_IDENTITY=-', 'CODE_SIGNING_ALLOWED=NO', 'CODE_SIGNING_REQUIRED=NO', 
                'PROVISIONING_PROFILE=', 'PROVISIONING_PROFILE_SPECIFIER=' 
            ])}

            return xcConfig.comandoRemoto(comandos).drop(1)
        }
    })
}
// Registro das tarefas de arquivamento para cada plataforma
tasks.register('archiveMacos', Exec) { xarchive(it, 'macos', 'macosx') }
tasks.register('archiveIos', Exec) { xarchive(it, 'ios', 'iphoneos') }
// Valida e assina o aplicativo, (não funciona, não tenho nenhuma chave de desenvolvedor válida)
Closure<Void> xexport = { Task tarefa, String platforma ->
    tarefa.description = 'Exporta o apliativo.xcarchive para AppStore'
    tarefa.group = 'Xcode Actions'
    tarefa.inputs.files(tasks.named("archive${platforma.capitalize()}")) // dependência implicita
    tarefa.outputs.file(xcConfig.eMac.map { Boolean eMac ->
        if (eMac) {
            String exportExt = (platforma == 'ios' ? 'ipa' : 'pkg')
            return "${pegaDir('derived-data', platforma)}/Exported-Products/Logger.${exportExt}"
        } else { return null }
    }).optional()

    tarefa.executable = pegaExecutavelBase()
    tarefa.argumentProviders.add(new CommandLineArgumentProvider() {
        @Input Provider<String> getXcodeProj() { xcConfig.xcodeProj }
        @Input Provider<String> getProjDir() { xcConfig.projDir }
        @Input Provider<String> getEMac() { xcConfig.eMac }

        @Override Iterable<String> asArguments() {
            String exportDir = "${pegaDir('derived-data', platforma)}/Exported-Poducts"
            String plistDir = "${getXcodeProj().get()}/exportOptions.plist"
            String localPlistDir = new File(getProjDir().get().asFile, plistDir).absolutePath
            // Comando de Exportação requer um .plist, criado em xcode-project
            return xcConfig.comandoRemoto([
                'xcrun', 'xcodebuild', '-exportArchive',
                '-archivePath', pegaArchiveDir(platforma),
                '-exportPath', exportDir,
                '-exportOptionsPlist', xcConfig.eMac.get() ? localPlistDir : plistDir
            ]).drop(1)
        }
    })
}
// Registra as tarefas de exportação para cada plataforma
tasks.register('exportMacos', Exec) { xexport(it, 'macos') }
tasks.register('exportIos', Exec) { xexport(it, 'ios') }
// Envia o app exportado para o App Store Connect
Closure<Void> xsubmit = { Task tarefa, String platforma ->
    tarefa.description = "Envia o pacote (${platforma}) exportado para o App Store Connect"
    tarefa.group = 'Xcode Actions'
    tarefa.inputs.files(tasks.named("export${platforma.capitalize()}"))

    tarefa.executable = pegaExecutavelBase()
    tarefa.argumentProviders.add(new CommandLineArgumentProvider() {
        @Override Iterable<String> asArguments() {
            String exportDir = "${pegaDir('derived-data', platforma)}/Exported-Poducts"
            String exportArq = (platforma == 'ios' ? 'ipa' : 'pkg')
            // Comando de Exportação requer um .plist, criado em xcode-project
            return xcConfig.comandoRemoto([
                'xcrun', 'altool', '--upload-app',
                '--username', appleIdProv.get(), 
                '--password', appleSenhaProv.get(),
                '--file', "${exportDir}/${xcConfig.nomeApp.get()}.${exportArq}" 
            ]).drop(1)
        }
    })
}
// Registra as tarefas de submissão para cada plataforma
tasks.register('submitIos', Exec) { xsubmit(it, 'ios') }
tasks.register('submitMacos', Exec) { xsubmit(it, 'macos') }
// Biblioteras para serem usadas no código
// dependencies {}