// Declaração dos plugins
// plugins {}
// Atalhos para facilitar a leitura
Object propsLocal = gradle.ext.propsLocal
// Definição de provedores para acesso à valores de configuração e diretórios
Provider<Directory> buildDirProv = project.layout.buildDirectory
Provider<Directory> instllDirProv = buildDirProv.dir('install/main')
Provider<Directory> genDirProv = buildDirProv.dir('tmp/generated')
Provider<Boolean> eWindowsProv = providers.systemProperty('os.name').map {
    it.toLowerCase().contains('windows')
}
Provider<Boolean> eLinuxProv = providers.systemProperty('os.name').map {
    it.toLowerCase().contains('linux')
}
Provider<String> appNomeProv = providers.gradleProperty('projNome')
Provider<String> espNomeProv = providers.gradleProperty('espolioDir').orElse('espolio')
Provider<String> linDonoProv = project.providers.provider { propsLocal.getProperty('lin.dono') }
Provider<String> linSedeProv = project.providers.provider { propsLocal.getProperty('lin.sede') }
Provider<String> linDirProv = project.providers.provider { propsLocal.getProperty('lin.dir') }
Provider<String> winDonoProv = project.providers.provider { propsLocal.getProperty('win.dono') }
Provider<String> winSedeProv = project.providers.provider { propsLocal.getProperty('win.sede') }
Provider<String> winDirProv = project.providers.provider { propsLocal.getProperty('win.dir') }
Provider<String> winDiscProv = project.providers.provider { 
    propsLocal.getProperty('unidade.win', 'C') 
}
Provider<Directory> espolioDirProv = project.rootProject.layout.projectDirectory.dir(espNomeProv)
Provider<Directory> projDirProv = project.providers.provider { project.layout.projectDirectory }
// Se necessário encapsula o comando em uma chamada ssh para a VM
Closure<List<String>> comandoRemoto = { String os, List<String> entradaCmds, String extDir = null ->
    if (eWindowsProv.get() && os == 'linux') {
        if (!linDonoProv.isPresent() || !linSedeProv.isPresent() || !linDirProv.isPresent()){
            throw new GradleException('Credenciais não configuradas pra Linux')
        }
        return [ // Cria a pasta base antes de dar o cd
            'ssh', "${linDonoProv.get()}@${linSedeProv.get()}", 
            "mkdir -p '${linDirProv.get()}' && cd '${linDirProv.get()}' && ${entradaCmds.join(' ')}"
        ]
    } else if (eLinuxProv.get() && os == 'windows') {
        if (!winDonoProv.isPresent() || !winSedeProv.isPresent() || !winDirProv.isPresent()){
            throw new GradleException('Credenciais não configuradas pra Windows')
        }
        return [ // Cria a pasta antes de dar o cd no Windows
            'ssh', "${winDonoProv.get()}@${winSedeProv.get()}", 
            "if not exist \"${winDirProv.get()}\" mkdir \"${winDirProv.get()}\" &",
            "cd /d \"${winDirProv.get()}\" && ${entradaCmds.join(' ')}"
        ]
    } else {
        String dirLocal = projDirProv.get().asFile.absolutePath
        if (eWindowsProv.get()) {
            // Se foi passado um caminho extra, injeta ele no início do PATH do Windows
            if (extDir != null) {
                return [
                    'cmd', '/c', "set \"PATH=${extDir};%PATH%\" &&" +
                    "cd /d \"${dirLocal}\" && ${entradaCmds.join(' ')}"
                ]
            } else {
                return ['cmd', '/c', "cd /d \"${dirLocal}\" && ${entradaCmds.join(' ')}"]
            }
        } else {
            return ['bash', '-c', "cd '${dirLocal}' && ${entradaCmds.join(' ')}"]
        }
    }
}
// Retorna arquivos para os artefatos de build
Closure<Provider<FileCollection>> pegaArquivos = { String subDir ->
    return project.layout.files(instllDirProv.map { it.dir(subDir) })
}
// Copiar recursos para a saída
Closure<Void> copiaRes = { File destinoDir ->
    File espolioDir = espolioDirProv.get().asFile
    if (!espolioDir.exists()) {
        println ">> AVISO: Pasta ${espNomeProv.get()} não encontrada em: ${espolioDir}"
        return
    }

    File recursDir = new File(destinoDir, 'recursos')
    if (!recursDir.exists()) { recursDir.mkdirs() }
    
    println ">> INFO: Copiando recursos de '${espolioDir.name}' para '${recursDir.name}'..."
    // Caminha recursivamente por todos os arquivos do espolio
    espolioDir.eachFileRecurse { File dir ->
        // Calcula o caminho relativo
        File destDir = new File(recursDir, espolioDir.toPath().relativize(dir.toPath()).toString())

        if (dir.isDirectory()) {
            destDir.mkdirs()
        } else {
            destDir.parentFile.mkdirs()
            // Copia substituindo se existir
            java.nio.file.Files.copy(
                dir.toPath(), 
                destDir.toPath(), 
                java.nio.file.StandardCopyOption.REPLACE_EXISTING)
        }
    }
}
// Converte arquivos de espolio para hpp
Closure<Void> embuteRes = {
    File espolioDir = espolioDirProv.get().asFile
    File saidaHPP = new File(genDirProv.get().asFile, "${espNomeProv.get()}.hpp")

    if (!espolioDir.exists()) { return }
    saidaHPP.parentFile.mkdirs()

    List<String> arqvs = []
    StringBuilder hpp = new StringBuilder()

    hpp.append('#pragma once\n')
    hpp.append('#include <string>\n')
    hpp.append('#include <vector>\n')
    hpp.append('#include <map>\n\n')
    hpp.append("namespace ${espNomeProv.get()} {\n")

    espolioDir.eachFileRecurse { File arq ->
        if (arq.isFile()) {
            String dir = espolioDir.toPath().relativize(
                arq.toPath()).toString().replace(File.separator, '/')
            String nome = dir.replaceAll('[^a-zA-Z0-9]', '_')
            byte[] bytes = arq.readBytes()
            
            hpp.append("    const unsigned char ${nome}[] = {")
            hpp.append(bytes.collect { String.format('0x%02x', it) }.join(', '))
            hpp.append('};\n')
            
            arqvs.add("\t\t{\"${dir}\", std::vector<uint8_t>(${nome}, ${nome} + sizeof(${nome}))}")
        }
    }

    hpp.append('\n\tinline std::vector<uint8_t> Obter(const std::string& caminho) {\n')
    hpp.append('\t\tstatic std::map<std::string, std::vector<uint8_t>> arquivos = {\n')
    hpp.append(arqvs.join(',\n'))
    hpp.append('\n\t\t};\n')
    hpp.append('\t\tif (arquivos.count(caminho)) return arquivos[caminho];\n')
    hpp.append('\t\treturn {};\n')
    hpp.append('\t}\n')
    hpp.append('}\n')

    String arquivo = hpp.toString()
    // Só salva no disco se o conteúdo realmente mudou
    if (!saidaHPP.exists() || saidaHPP.text != arquivo) {
        saidaHPP.text = arquivo
    }
}
// Configura o ícone do aplicativo
Closure<Void> desktop = { String appNome, String caminhoExe ->
    File iconePNG = new File(buildDirProv.get().asFile, 'app_linux.png')

    File localIconsDir = new File(
        System.getProperty('user.home'), '.local/share/icons/hicolor/512x512/apps')
    if (!localIconsDir.exists()) localIconsDir.mkdirs()

    File iconeDir = new File(localIconsDir, "${appNome}.png")
    if (iconePNG.exists()) {
        java.nio.file.Files.copy(
            iconePNG.toPath(), 
            iconeDir.toPath(), 
            java.nio.file.StandardCopyOption.REPLACE_EXISTING
        )
    }
    // Acessa a pasta oculta de aplicativos do usuário
    File localAppsDir = new File(System.getProperty('user.home'), '.local/share/applications')
    if (!localAppsDir.exists()) { localAppsDir.mkdirs() } // cria a pasta se não existir
    
    new File(localAppsDir, "${appNome}.desktop").text = """
        [Desktop Entry]
        Version=1.0
        Type=Application
        Name=${appNome}
        Exec=\"${caminhoExe}\"
        Icon=${appNome}
        Terminal=false
        StartupWMClass=Logger
        Categories=Utility;Development;
        """.stripIndent().trim()
    
    try {
        // Força o GNOME/Wayland a ler a pasta e atualizar os ícones na hora
        ([ 'update-desktop-database', 
            localAppsDir.absolutePath
        ]).execute().waitForProcessOutput(System.out, System.err)

        ([ 'gtk-update-icon-cache', '-f', '-t', 
            (new File(System.getProperty('user.home'), '.local/share/icons/hicolor')).absolutePath
        ]).execute().waitForProcessOutput(System.out, System.err)
    } catch(Exception e) {
        println '>> AVISO: update-desktop-database não rodou, mas o arquivo foi criado.'
    }
}
// Coleta as flags de compilação
Closure<List<String>> pegaFlagsComp = { String alvo, String arqtt, String config, Boolean eRemoto ->
    List<String> flags = ['-std=c++26', '-Os']
    
    if (alvo.toLowerCase() == 'linux') { flags << '-I/usr/include/jsoncpp' }
    
    flags << (arqtt == 'X86' ? '-m32' : '-m64')
    // Diferencia Caminhos Locais Absolutos dos Caminhos SSH Relativos
    if (eRemoto) {
        flags.addAll(['-Isrc/main/headers', '-Isrc/main/bib/svg'])
        if (eWindowsProv.get() && alvo.toLowerCase() == 'windows') {
            flags << "-I${genDirProv.get().asFile.absolutePath.replace(File.separator, '/')}"
        } else {
            flags.addAll(['-Ibuild/tmp/generated', '-Ibuild/tmp'])
        }
    } else {
        flags.addAll([
            "-I${projDirProv.get().asFile.absolutePath}/src/main/bib/svg",
            "-I${genDirProv.get().asFile.absolutePath.replace(File.separator, '/')}"
        ])
    }
    return flags
}
// Coleta as flags de Linkagem
Closure<List<String>> pegaFlagsLink = { String alvo, String arqtt, String config, Boolean eTeste ->
    List<String> flags = []
    if (config == 'Release') { flags.addAll(['-s']) }

    if (alvo.toLowerCase() == 'windows') {
        flags.addAll([
            '-static', 
            '-Wl,--start-group', 
            '-lgdi32', 
            '-luser32', 
            '-luxtheme', 
            '-loleaut32', 
            '-lcomctl32', 
            '-ljsoncpp'
        ])
        
        if (eTeste) { flags.addAll(['-lgtest', '-lgtest_main', '-lpthread']) }
         
        flags.addAll(['-Wl,--end-group', '-static-libgcc', '-static-libstdc++'])
        // Esconde o console se for Release e não for Teste
        if (config == 'Release' && !eTeste) { flags << '-mwindows' }
    } 
    else if (alvo.toLowerCase() == 'linux') {
        if (arqtt == 'X86') {
            flags.addAll([
                '-m32', 
                '-Wl,-m,elf_i386', 
                '-L/usr/lib/i386-linux-gnu', 
                '/usr/lib/i386-linux-gnu/libjsoncpp.a'
            ])
        } else {
            flags.addAll([
                '-m64', 
                '-Wl,-m,elf_x86_64', 
                '-L/usr/local/lib', 
                '-L/usr/lib/x86_64-linux-gnu'
            ])
        }
        flags.addAll(['-Wl,-Bstatic', '-ljsoncpp'])
        
        if (eTeste) flags.addAll(['-lgtest', '-lgtest_main'])
        
        flags.addAll(['-Wl,-Bdynamic', '-lX11', '-pthread', '-static-libgcc', '-static-libstdc++'])
    }
    return flags
}
// Envia os arquivos para a máquina virtual Linux
tasks.register('syncToLinux') {
    group = 'C++ Actions'
    description = 'Sincroniza os arquivos fonte para a VM Linux via SSH'
    onlyIf { eWindowsProv.get() }
    // Regras de inputs
    mustRunAfter tasks.named('criaEspolio') // roda a closure geradora antes de compilar
    inputs.files(tasks.named('criaEspolio'))
    inputs.dir project.file('src')
    inputs.dir espolioDirProv
    outputs.upToDateWhen { true } // executa só 1 vez
    
    doFirst {
        // Prepara as pastas no Linux, adiciona o tmp e icones explicitamente
        comandoRemoto('linux', 
            ['mkdir', '-p', "${linDirProv.get()}/build/tmp", "${linDirProv.get()}/build/icons"]
        ).execute().waitForProcessOutput(System.out, System.err)
    }
    
    doLast {
        String sshLogin = "${linDonoProv.get()}@${linSedeProv.get()}"
        String base = linDirProv.get()
        Directory projDir = projDirProv.get()
        
        println '>> INFO: [Linux] Enviando arquivos fonte e recursos...'
        Process processoSCP = (['scp', '-r', '-p', 
            projDir.dir('src').asFile.absolutePath.replace(File.separator, '/'), 
            espolioDirProv.get().asFile.absolutePath.replace(File.separator, '/'), 
            "${sshLogin}:${base}/"
        ]).execute(null, projDir.asFile)
        processoSCP.waitForProcessOutput(System.out, System.err)
        if (processoSCP.exitValue() != 0) throw new GradleException('Falha no upload dos fontes!')
        
        println '>> INFO: [Linux] Enviando header gerado...'
        (['scp', '-r', '-p', 
            genDirProv.get().asFile.absolutePath, "${sshLogin}:${base}/build/tmp/"
        ]).execute(null, projDir.asFile).waitForProcessOutput(System.out, System.err)
        
        println '>> INFO: [Linux] Enviando ícone...'
        File iconePNG = new File(buildDirProv.get().asFile, 'app_linux.png')
        if (iconePNG.exists()) {
            (['scp', '-p', 
                iconePNG.absolutePath, "${sshLogin}:${base}/build/icons/"
            ]).execute(null, projDir.asFile).waitForProcessOutput(System.out, System.err)
        }
        
        println '>> INFO: Sincronização para Linux concluída!'
    }
}
// Envia os arquivos para a máquina virtual Windows
tasks.register('syncToWindows') {
    group = 'C++ Actions'
    description = 'Sincroniza os arquivos fonte para a VM Windows via SSH'
    onlyIf { eLinuxProv.get() }
    mustRunAfter tasks.named('criaEspolio') // roda a closure geradora antes de compilar
    inputs.files(tasks.named('criaEspolio'))
    inputs.dir project.file('src')
    inputs.dir espolioDirProv
    outputs.upToDateWhen { true } // executa só 1 vez
    
    doFirst {
        // Prepara as pastas no windows
        comandoRemoto('windows', 
            ['mkdir', '-p', winDirProv.get().replace(File.separator, '/')]
        ).execute().waitForProcessOutput(System.out, System.err)
    }
    
    doLast {
        String sshLogin = "${winDonoProv.get()}@${winSedeProv.get()}"
        String base = winDirProv.get()
        Directory projDir = projDirProv.get()
        
        println '>> INFO: [Windows] Enviando arquivos fonte e recursos...'
        Process processoSCP = (['scp', '-r', '-p', 
            projDir.dir('src').asFile.absolutePath.replace(File.separator, '/'), 
            espolioDirProv.get().asFile.absolutePath.replace(File.separator, '/'), 
            "${sshLogin}:${base}/"
        ]).execute(null, projDir.asFile)
        processoSCP.waitForProcessOutput(System.out, System.err)
        if (processoSCP.exitValue() != 0) throw new GradleException('Falha no upload dos fontes!')
        
        println '>> INFO: [Windows] Enviando header gerado...'
        (['scp', '-r', '-p', 
            genDirProv.get().asFile.absolutePath, "${sshLogin}:${base}/build/tmp/"
        ]).execute(null, projDir.asFile).waitForProcessOutput(System.out, System.err)
        
        println '>> INFO: [Windows] Enviando ícones e RC...'
        File obj32Arq = new File(buildDirProv.get().asFile, 'icone32.o')
        File obj64Arq = new File(buildDirProv.get().asFile, 'icone64.o')
        if (obj32Arq.exists() && obj64Arq.exists()) {
            (['scp', '-p', obj32Arq.absolutePath, obj64Arq.absolutePath, 
                "${sshLogin}:${base}/build/icons/"
            ]).execute(null, projDir.asFile).waitForProcessOutput(System.out, System.err)
        }

        println '>> INFO: Sincronização para Windows concluída!'
    }
}
// Limpa o ambiente para melhores resultados
tasks.register('cleanC') {
    group = 'C++ Actions'
    description = 'Limpa os diretórios de build C++ localmente e nas VMs (via SSH)'

    doLast {
        File dirLocal = buildDirProv.get().asFile
        if (dirLocal.exists()) {
            println '>> INFO: [Local] Limpando diretório de build C++...'
            dirLocal.deleteDir()
        }
        // Limpeza Remota na VM Linux
        if (eWindowsProv.get()) {
            try {
                println '>> INFO: [Linux] Limpando diretório remoto via SSH...'
                // Manda um rm -rf na pasta build da VM Linux
                comandoRemoto(
                    'linux', ["rm -rf \'${linDirProv.get()}/build\'"]
                ).execute().waitForProcessOutput(System.out, System.err)
            } catch(Exception e) { 
                println '>> AVISO: Não foi possível limpar a VM Linux. Ela pode estar desligada.' 
            }
        }
        // Limpeza Remota na VM Windows
        if (eLinuxProv.get()) {
            try {
                println '>> INFO: [Windows] Limpando diretório remoto via SSH...'
                // Manda um rmdir (cmd) na pasta build da VM Windows
                comandoRemoto(
                    'windows', ["rmdir /s /q \"${winDirProv.get()}/build\""]
                ).execute().waitForProcessOutput(System.out, System.err)
            } catch(Exception e) { 
                println '>> AVISO: Não foi possível limpar a VM Windows. Ela pode estar desligada.' 
            }
        }
    }
}
// Certifica que o espolio entrará nos arquivos
tasks.register('criaEspolio') {
    group = 'C++ Setup'
    description = 'Converte os arquivos dos recursos em um Header C++'
    inputs.dir espolioDirProv
    outputs.file(new File(genDirProv.get().asFile, "${espNomeProv.get()}.hpp"))
    
    doLast { embuteRes() }
}
// Verifica e instala dependências automaticamente
tasks.register('instalaDeps', Exec) {
    group = 'setup'
    description = 'Instala dependências do Pacman via MSYS2 Bash'
    outputs.upToDateWhen { false } // sempre executa

    doLast {
        if (eWindowsProv.get()) {
            println '>> INFO: Instalando dependências do Windows...'
            List<String> winDeps = [
                'mingw-w64-ucrt-x86_64-jsoncpp', 
                'mingw-w64-i686-jsoncpp',
                'mingw-w64-ucrt-x86_64-toolchain', 
                'mingw-w64-i686-toolchain',
                'mingw-w64-ucrt-x86_64-imagemagick', 
                'mingw-w64-ucrt-x86_64-librsvg',
                'mingw-w64-ucrt-x86_64-gtest', 
                'mingw-w64-i686-gtest'
            ]
            // Chamando o pacman do msys2
            try {
                commandLine comandoRemoto('windows', [
                    "${winDiscProv.get()}:/msys64/usr/bin/bash.exe -l -c",
                    "\"pacman -S --needed --noconfirm ${winDeps.join(' ')}\""
                ])
            } catch(Exception e) { println '>> AVISO: VM Windows indisponível.' }
        } else {
            println '>> INFO: Instalando dependências do Linux...'
            List<String> linDeps = [
                'build-essential', 
                'cmake', 
                'g++-multilib', 
                'libc6-dev-i386',
                'libx11-dev', 
                'libx11-dev:i386', 
                'libgtest-dev', 
                'libjsoncpp-dev',
                'libjsoncpp-dev:i386', 
                'imagemagick', 
                'librsvg2-bin'
            ]
            try {
                commandLine comandoRemoto('linux', 
                    ["sudo bash -c \'apt update && apt install -y ${linDeps.join(' ')}\'"]
                )
            } catch(Exception e) { println '>> AVISO: VM Linux indisponível.' }
        }
    }
}
// Centralização de compilação
Closure<Void> cbuild = { Task tarefa, String alvo, String arqtt, String config ->
    String osAlvo = alvo.toLowerCase()
    String appDir = "build/install/main/${config}/${alvo}/${arqtt}/lib".toLowerCase()

    tarefa.group = 'C++ Actions'
    tarefa.description = "Compila nativamente via SSH em ${alvo}-${arqtt}"
    // O build aguarda o Sync, se for remoto, ou a Geração, se for local
    if (osAlvo == 'windows' && eLinuxProv.get()) {
        tarefa.inputs.files(tasks.named('syncToWindows'))
    } else if (osAlvo == 'linux' && eWindowsProv.get()) {
        tarefa.inputs.files(tasks.named('syncToLinux'))
    } else {
        tarefa.inputs.files(tasks.named('criaEspolio'))
        tarefa.inputs.files(tasks.named((osAlvo == 'windows' ? 'winIco' : 'linIco')))
    }

    tarefa.doLast {
        List<String> gppFlags = []
        if (osAlvo == 'windows') {
            gppFlags.add(
                "${winDiscProv.get()}:/msys64/${arqtt == 'X86' ? 'mingw32' : 'ucrt64'}/bin/g++.exe"
            )
        } else {
            gppFlags << 'g++'
        }

        gppFlags.addAll(pegaFlagsComp(alvo, arqtt, config, true)) // injeção de flags

        Directory projDir = projDirProv.get()
        File cppDir = new File(projDir.asFile, 'src/main/cpp')
        if (cppDir.exists()) {
            cppDir.eachFileRecurse(groovy.io.FileType.FILES) { File arq ->
                if (arq.name.endsWith('.cpp')) {
                    gppFlags.add(projDir.asFile.toPath().relativize(
                        arq.toPath()).toString().replace(File.separator, '/')
                    )
                }
            }
        }
        // Insere do ícone do Windows
        if (osAlvo == 'windows') {
            if (eWindowsProv.get()) { 
                gppFlags.add(
                    (new File(buildDirProv.get().asFile, 
                        (arqtt == 'X86' ? 'icone32.o' : 'icone64.o')
                    )).absolutePath.replace(File.separator, '/')
                )
            } else { 
                gppFlags << (arqtt == 'X86' ? 'build/icons/icone32.o' : 'build/icons/icone64.o')
            }
        }

        gppFlags.addAll(pegaFlagsLink(alvo, arqtt, config, false)) // injeção de flags
        
        File rootDir = projDir.asFile.parentFile // cria a pasta final na VM

        if (eWindowsProv.get() && osAlvo == 'windows') {
            new File(rootDir, appDir).mkdirs() // cria localmente na raiz do Windows
        } else {
            String dirCmd
            if (osAlvo == 'windows') {
                dirCmd = "if not exist \"${appDir.replace(File.separator, '/')}\""
                dirCmd += "mkdir \"${appDir.replace(File.separator, '/')}\""
            } else {
                dirCmd = "mkdir -p '${appDir}'"
            } 
            comandoRemoto(osAlvo, [dirCmd]).execute().waitForProcessOutput(System.out, System.err)
        }
        String appNome = appNomeProv.get()
        String nomeExe = alvo == 'Windows' ? "${appNome}.exe" : appNome
        String saidaDir // saída do binário
        if (eWindowsProv.get() && osAlvo == 'windows') {
            saidaDir = new File(rootDir, 
                "${appDir}/${nomeExe}").absolutePath.replace(File.separator, '/')
        } else {
            // Na VM Remota, o saidaDir é puro e direto
            saidaDir = "${appDir}/${nomeExe}"
            if (osAlvo == 'windows') saidaDir = saidaDir.replace(File.separator, '/')
        }
        gppFlags << '-o' << "\"${saidaDir}\""

        println ">> INFO: Compilando [${alvo}-${arqtt}] nativamente na VM..."
        // Passa o caminho exato do MSYS2 para blindar as DLLs do Windows
        String dirDireto = null
        if (eWindowsProv.get() && osAlvo == 'windows') {
            dirDireto = "${winDiscProv.get()}:/msys64/${arqtt == 'X86' ? 'mingw32' : 'ucrt64'}/bin"
        }
        Process processoCompilar = comandoRemoto(osAlvo, [gppFlags.join(' ')], dirDireto).execute()
        processoCompilar.waitForProcessOutput(System.out, System.err) // devolve a saída limpa
        
        if (processoCompilar.exitValue() != 0) {
            throw new GradleException("Falha na compilação do C++ [${alvo}-${arqtt}]")
        }
        println ">> INFO: Sucesso! Binário salvo em: ${saidaDir}"
    }
}
// Tarefas de build
tasks.register('buildWin64') { cbuild(it, 'Windows', 'X86-64', 'Debug') }
tasks.register('buildWin64Release') { cbuild(it, 'Windows', 'X86-64', 'Release') }
tasks.register('buildWin32') { cbuild(it, 'Windows', 'X86', 'Debug') }
tasks.register('buildWin32Release') { cbuild(it, 'Windows', 'X86', 'Release') }
tasks.register('buildLin64') { cbuild(it, 'Linux', 'X86-64', 'Debug') }
tasks.register('buildLin64Release') { cbuild(it, 'Linux', 'X86-64', 'Release') }
tasks.register('buildLin32') { cbuild(it, 'Linux', 'X86', 'Debug') }
tasks.register('buildLin32Release') { cbuild(it, 'Linux', 'X86', 'Release') }
// Closure centralização de execução
Closure<Void> crun = { Task tarefa, String alvo, String arqtt, String config ->
    String appDir = "${config}/${alvo}/${arqtt}/lib".toLowerCase()
    String tarefaNativaNome = "install${config}${alvo}${arqtt}"
    String buildNome = "build${alvo == 'Windows' ? 'Win' : 'Lin'}${arqtt == 'X86' ? '32' : '64'}"

    tarefa.group = 'C++ Actions'
    tarefa.description = "Executa o binário ${alvo}-${arqtt}"
    tarefa.inputs.files(tasks.named("${buildNome}${config == 'Release' ? 'Release' : ''}"))
    tarefa.inputs.files(pegaArquivos(appDir))
    if (tasks.findByName(tarefaNativaNome)) {
        tarefa.inputs.files(tasks.named(tarefaNativaNome))
        tarefa.mustRunAfter tasks.named(tarefaNativaNome)
    }
    tarefa.outputs.upToDateWhen { false } // sempre executa

    tarefa.doFirst {
        String appNome = appNomeProv.get()
        String osAlvo = alvo.toLowerCase()
        String nomeExe = alvo == 'Windows' ? "${appNome}.exe" : appNome
        
        List<String> cmds
        if (osAlvo == 'windows') {
            if (eWindowsProv.get()) {
                String local = new File(projDirProv.get().asFile.parentFile, 
                    "build/install/main/${appDir}").absolutePath
                cmds = ["cd /d \"${local}\"", '&&', 'start', '\"\"', nomeExe]
            } else {
                String remoto = "build/install/main/${appDir}"
                cmds = [
                    "cd \"${remoto.replace(File.separator, '/')}\"", 
                    '&&', 'start', '\"\"', nomeExe
                ]
            }
        } else {
            cmds = [
                'export DISPLAY=:0', '&&',
                'export XAUTHORITY=$(ls /run/user/$(id -u)/gdm/Xauthority',
                '/run/user/$(id -u)/.mutter-Xwaylandauth*',
                '/run/user/$(id -u)/Xauthority',
                '~/.Xauthority 2>/dev/null | head -n 1)', '&&', 
                "cd \'build/install/main/${appDir}\'", '&&', 
                "setsid sh -c \'exec ./${nomeExe} > /dev/null 2>&1 < /dev/null &\' > /dev/null 2>&1"
            ]
        }
        // Ícone do desktop só faz sentido se estiver rodando localmente no Linux
        if (osAlvo == 'linux' && eLinuxProv.get()) {
            desktop(appNome, new File(instllDirProv.get().dir(appDir).asFile, nomeExe).absolutePath)
        }

        println ">> INFO: Executando ${alvo}..."
        String dirDireto = null
        if (eWindowsProv.get() && osAlvo == 'windows') {
            dirDireto = "${winDiscProv.get()}:/msys64/${arqtt == 'X86' ? 'mingw32' : 'ucrt64'}/bin"
        }
        Process precessoExecutar = comandoRemoto(osAlvo, cmds, dirDireto).execute()
        precessoExecutar.waitFor() // tem que ser waitFor() e não waitForProcessOutput()
        if (precessoExecutar.exitValue() != 0) { throw new GradleException('A execução falhou.') }
    }
}
// Tarefas de execução
tasks.register('runWin64') { crun(it, 'Windows', 'X86-64', 'Debug') }
tasks.register('runWin64Release') { crun(it, 'Windows', 'X86-64', 'Release') }
tasks.register('runWin32') { crun(it, 'Windows', 'X86', 'Debug') }
tasks.register('runWin32Release') { crun(it, 'Windows', 'X86', 'Release') }
tasks.register('runLin64') { crun(it, 'Linux', 'X86-64', 'Debug') }
tasks.register('runLin64Release') { crun(it, 'Linux', 'X86-64', 'Release') }
tasks.register('runLin32') { crun(it, 'Linux', 'X86', 'Debug') }
tasks.register('runLin32Release') { crun(it, 'Linux', 'X86', 'Release') }
// Centralização de teste
Closure<Void> ctest = { Task tarefa, String alvo, String arqtt, String config ->
    String testDir = "${alvo}/${arqtt}/lib".toLowerCase()
    String tarefaNativaNome = "installTest${alvo}${arqtt}"
    String buildNome = "build${alvo == 'Windows' ? 'Win' : 'Lin'}${arqtt == 'X86' ? '32' : '64'}"

    tarefa.group = 'C++ Actions' // grupo padrão para testes
    tarefa.description = "Executa os testes unitários em ${alvo}-${arqtt}"
    tarefa.inputs.files(tasks.named("${buildNome}${config == 'Release' ? 'Release' : ''}"))
    if (tasks.findByName(tarefaNativaNome)) {
        tarefa.inputs.files(tasks.named(tarefaNativaNome))
        tarefa.mustRunAfter tasks.named(tarefaNativaNome)
    }
    tarefa.outputs.upToDateWhen { false } // testes devem sempre rodar

    tarefa.doFirst {
        String appTestNome = "${appNomeProv.get()}Test" 
        String osAlvo = alvo.toLowerCase()
        String nomeExe = alvo == 'Windows' ? "${appTestNome}.exe" : appTestNome        
        // Cópia local de recursos antes do teste
        File exeDir = buildDirProv.get().dir('install/test').dir(testDir).asFile
        copiaRes(exeDir)

        if (osAlvo == 'linux') {
            println ">> INFO: Compilando Testes [${alvo}-${arqtt}] nativamente na VM..."
            String dirRemoto = "build/install/test/${testDir}"
            List<String> gppTestcmds = ['g++']
            gppTestcmds.addAll(pegaFlagsComp(alvo, arqtt, config, true))
            gppTestcmds.addAll(
                "\$(find src/main/cpp -name \'*.cpp\' ! -name \'app.cpp\')",
                "\$(find src/test/cpp -name \'*.cpp\')",
                '-o', "\'${dirRemoto}/${nomeExe}\'"
            )
            gppTestcmds.addAll(pegaFlagsLink(alvo, arqtt, config, true))

            Process processoCompilar = comandoRemoto(osAlvo, [
                "mkdir -p \'${dirRemoto}\'", '&&',
                gppTestcmds.join(' ')
            ]).execute()
            processoCompilar.waitForProcessOutput(System.out, System.err)

            if (processoCompilar.exitValue() != 0) {
                throw new GradleException('Falha ao compilar testes no Linux')
            }
        }
        
        List<String> cmds
        if (osAlvo == 'windows') {
            if (eWindowsProv.get()) {
                // Usa o diretório absoluto local do exeDir
                cmds = ["cd /d \"${exeDir.absolutePath}\"", '&&', nomeExe]
            } else {
                String dirRemoto = "build/install/test/${testDir}"
                cmds = ["cd \"${dirRemoto.replace(File.separator, '/')}\"", '&&', nomeExe]
            }
        } else {
            cmds = [
                'export DISPLAY=:0', '&&',
                'export XAUTHORITY=$(ls /run/user/$(id -u)/gdm/Xauthority',
                '/run/user/$(id -u)/.mutter-Xwaylandauth*',
                '/run/user/$(id -u)/Xauthority',
                '~/.Xauthority 2>/dev/null | head -n 1)', 
                '&&', "cd \'build/install/test/${testDir}\'", '&&', "./${nomeExe}"
            ]
        }

        println ">> INFO: Executando testes unitários em ${alvo}..."
        String dirDireto = null
        if (eWindowsProv.get() && osAlvo == 'windows') {
            dirDireto = "${winDiscProv.get()}:/msys64/${arqtt == 'X86' ? 'mingw32' : 'ucrt64'}/bin"
        }
        Process processoTestar = comandoRemoto(
            osAlvo, cmds, dirDireto
        ).execute()
        processoTestar.waitForProcessOutput(System.out, System.err) // no teste, espera GTest acabar
        
        if (processoTestar.exitValue() != 0) {
            throw new GradleException('Os testes unitários do C++ falharam.')
        }
    }
}
// Tarefas de Teste
tasks.register('testWin64') { ctest(it, 'Windows', 'X86-64', 'Debug') }
tasks.register('testWin64Release') { ctest(it, 'Windows', 'X86-64', 'Release') }
tasks.register('testWin32') { ctest(it, 'Windows', 'X86', 'Debug') }
tasks.register('testWin32Release') { ctest(it, 'Windows', 'X86', 'Release') }
tasks.register('testLin64') { ctest(it, 'Linux', 'X86-64', 'Debug') }
tasks.register('testLin64Release') { ctest(it, 'Linux', 'X86-64', 'Release') }
tasks.register('testLin32') { ctest(it, 'Linux', 'X86', 'Debug') }
tasks.register('testLin32Release') { ctest(it, 'Linux', 'X86', 'Release') }
// Cria um objeto para o icone do aplicativo
Closure<Void> criaIcoWin = { File fundoSVG, File frenteSVG, File icoArq, File rcArq, 
    File obj32Arq, File obj64Arq ->
    if (!fundoSVG.exists()) throw new GradleException('Faltou o SVG de Fundo!')
    if (!frenteSVG.exists()) throw new GradleException('Faltou o SVG de Frente!')
    
    File buildDir = icoArq.parentFile
    if (!buildDir.exists()) buildDir.mkdirs()
        
    String msysDir = winDiscProv.get()
    String magickCmd = eWindowsProv.get() ? "${msysDir}:/msys64/ucrt64/bin/magick.exe" : 'magick'

    List<String> mesclaSVG = [
        magickCmd,
        '-background', 'none',
        fundoSVG.absolutePath, // carrega a imagem de trás
        frenteSVG.absolutePath, // carrega a imagem da frente
        '-gravity', 'center', // centraliza o alinhamento
        '-composite', // mescla as duas imagens
        '-define', 'icon:auto-resize=256,128,64,48,32,16', 
        icoArq.absolutePath // salva o resultado
    ]
    Process prcessoMesclar = mesclaSVG.execute()
    prcessoMesclar.waitForProcessOutput(System.out, System.err)
    if (prcessoMesclar.exitValue() != 0) { throw new GradleException('Falha ao mesclar') }

    rcArq.text = "id ICON \"${icoArq.absolutePath.replace(File.separator, '/')}\""

    Closure<Void> rodaWindres = { String cmd, File objArq, String extraDir ->
        ProcessBuilder pb = new ProcessBuilder(cmd, rcArq.absolutePath, '-o', objArq.absolutePath)
        
        if (eWindowsProv.get() && extraDir != null) {
            // Injeta a pasta bin exata no início do path do Windows
            pb.environment().put(
                'PATH', extraDir + File.pathSeparator + pb.environment().get('PATH')
            )
        }
        
        Process processo = pb.start()
        processo.waitForProcessOutput(System.out, System.err)
        if (processo.exitValue() != 0) {
            throw new GradleException("Falha no windres para ${objArq.name}")
        }
    }
    // Injeção isolada para 32 e 64 bits
    if (eWindowsProv.get()) {
        rodaWindres("${msysDir}:/msys64/mingw32/bin/windres.exe", 
            obj32Arq, "${msysDir}:/msys64/mingw32/bin")
        rodaWindres("${msysDir}:/msys64/ucrt64/bin/windres.exe", 
            obj64Arq, "${msysDir}:/msys64/ucrt64/bin")
    } else {
        rodaWindres('i686-w64-mingw32-windres', obj32Arq, null)
        rodaWindres('x86_64-w64-mingw32-windres', obj64Arq, null)
    }
}
// Tarefa Mestra que administra a Closure
tasks.register('winIco') {
    group = 'C++ Actions'
    description = 'Administra a conversão e compilação do ícone do Windows'

    Provider<RegularFile> fundoSvgProv = espolioDirProv.map { it.file('icones/appBackground.svg') }
    Provider<RegularFile> frenteSvgProv = espolioDirProv.map { it.file('icones/appForeground.svg') }
    Provider<RegularFile> obj32ArqProv = buildDirProv.map { it.file('icone32.o') }
    Provider<RegularFile> obj64ArqProv = buildDirProv.map { it.file('icone64.o') }

    inputs.files(fundoSvgProv, frenteSvgProv)
    outputs.files(obj32ArqProv, obj64ArqProv)
    
    doLast {
        File fundoSVG = fundoSvgProv.get().asFile
        File frenteSVG = frenteSvgProv.get().asFile
        File icoArq = buildDirProv.get().file('app.ico').asFile
        File rcArq = buildDirProv.get().file('app.rc').asFile
        File obj32Arq = obj32ArqProv.get().asFile
        File obj64Arq = obj64ArqProv.get().asFile
        criaIcoWin(fundoSVG, frenteSVG, icoArq, rcArq, obj32Arq, obj64Arq)
    }
}
// Tarefa para o ícone do Linux
tasks.register('linIco') {
    group = 'C++ Actions'
    description = 'Gera o ícone PNG do aplicativo para Linux'

    Provider<RegularFile> fundoSvgProv  = espolioDirProv.map { it.file('icones/appBackground.svg') }
    Provider<RegularFile> frenteSvgProv = espolioDirProv.map { it.file('icones/appForeground.svg') }
    Provider<RegularFile> pngArqProv = buildDirProv.map { it.file('app_linux.png') }
    
    inputs.files(fundoSvgProv, frenteSvgProv)
    outputs.file pngArqProv
    
    doLast {
        File fundoSVG = fundoSvgProv.get().asFile
        File frenteSVG = frenteSvgProv.get().asFile
        File pngArq = pngArqProv.get().asFile
        
        if (!fundoSVG.exists()) throw new GradleException('Faltou o SVG de Fundo!')
        if (!frenteSVG.exists()) throw new GradleException('Faltou o SVG de Frente!')
        
        File buildDir = pngArq.parentFile
        if (!buildDir.exists()) buildDir.mkdirs()
            
        String msysDir = "${winDiscProv.get()}:/msys64/ucrt64/bin/magick.exe"
        String magickCmd = eWindowsProv.get() ? "${msysDir}" : 'magick'
        List<String> mesclaSVG = [
            magickCmd,
            '-background', 'none',
            fundoSVG.absolutePath, 
            frenteSVG.absolutePath, 
            '-gravity', 'center', '-composite', 
            '-resize', '2048x2048', 
            pngArq.absolutePath 
        ]
        
        StringBuilder err = new StringBuilder()
        Process processo = mesclaSVG.execute()
        processo.waitForProcessOutput(System.out, err)
        if (processo.exitValue() != 0) {
            throw new GradleException("Falha ao gerar o ícone do Linux: ${err.toString().trim()}")
        }
    }
}
Closure<List> pegeDefinicoes = { String name -> return [
    name.contains('Release') ? 'Release' : 'Debug',
    name.contains('Windows') || name.contains('windows') ? 'Windows' : 'Linux',
    name.contains('X86') && !name.contains('X86-64') && !name.contains('x86_64') ? 'X86' : 'X86-64',
    name.contains('Test') || name.contains('test')
]}
// Faz a compilação C++ depender da geração desse arquivo primeiro
tasks.withType(CppCompile).configureEach {
    mustRunAfter tasks.named('criaEspolio') // roda a closure geradora antes de compilar
    inputs.files(tasks.named('criaEspolio'))
    
    String config, alvo, arqtt // false = Native/Local
    (config, alvo, arqtt) = pegeDefinicoes(name)
    compilerArgs.addAll(project.providers.provider { pegaFlagsComp(alvo, arqtt, config, false)})
}
// Modifica a criação do executále para usar as bibliotecas necessárias
tasks.withType(LinkExecutable).configureEach {
    String config, alvo, arqtt
    boolean eTest 
    (config, alvo, arqtt, eTest) = pegeDefinicoes(name)
    linkerArgs.addAll(project.providers.provider { pegaFlagsLink(alvo, arqtt, config, eTest) })
}
// Biblioteras para serem usadas no código
// dependencies {}