// Delaração de plugins
plugins {
    alias libs.plugins.groovyGradle
}

dependencies {
    implementation (libs.proguard)
}
// Alteração da saída de build (if para burlar os erros do VSCode)
if (gradle.parent != null) {
    Directory projDir = project.gradle.parent.rootProject.layout.projectDirectory
    Provider<String> saidaDirProv = libs.versions.valores.buildDir.buildLogic
    layout.buildDirectory = projDir.dir(saidaDirProv)
}