// Busca um arquivo que possua a propriedade buildlogicNome para definir como propsRaiz
final Properties propsRaiz = new Properties()
FileInputStream fileInputStream = null
settingsDir.parentFile.listFiles().any { final File arq ->
    if (arq.isFile() && arq.canRead()) {
        fileInputStream = new FileInputStream(arq)
        propsRaiz.load(fileInputStream)
        if (propsRaiz.buildlogicNome != null) { return true } 
        else { propsRaiz.clear() }
    }
}
fileInputStream.close();
gradle.ext.buildDirBuildLogic = propsRaiz.buildDirBuildLogic // compartilha para o build-gradle
// Resolução de dependências
dependencyResolutionManagement {
    // Aonde buscar para cumprir as dependências
    repositories {
        google() // repositório oficial do google
        mavenCentral() // dependências de java e android
        gradlePluginPortal() // dependências especificas do gradle
    }
    // Acesso ao libs.versions.toml
    versionCatalogs {
        // Busca e define o libs.versions.toml como libs e usa como catálogo de versão
        create(propsRaiz.libsNome) {
            from(files(propsRaiz.libsDir))
        }
    }
}

rootProject.name = propsRaiz.buildlogicNome // nome da pasta do projeto