// Busca um arquivo que possua a propriedade buildlogicNome para definir como propsRaiz
final Properties propsRaiz = new Properties()
settingsDir.parentFile.listFiles().any { final File arq ->
    if (arq.isFile() && arq.canRead()) {
        arq.withInputStream { propsRaiz.load(it) }
        if (propsRaiz.buildlogicNome != null) { return true } 
        else { propsRaiz.clear() }
    }
}
// Alteração da saída de build do build-logic
gradle.rootProject { if (propsRaiz.buildDirBuildLogic) { it.layout.buildDirectory.set(
    new File(settingsDir.parentFile, propsRaiz.buildDirBuildLogic)
)}}
// Resolução de dependências
dependencyResolutionManagement {
    // Aonde buscar para cumprir as dependências
    repositories {
        google() // repositório oficial do google
        mavenCentral() // dependências de java e android
        gradlePluginPortal() // dependências especificas do gradle
    }
    // Acesso ao libs.versions.toml
    versionCatalogs {
        // Busca e define o libs.versions.toml como libs e usa como catálogo de versão
        create(propsRaiz.libsNome) {
            from(files(propsRaiz.libsDir))
        }
    }
}

rootProject.name = propsRaiz.buildlogicNome // nome da pasta do projeto